import {currentHr,hrDb,hrError} from '@/lib/hrServer'
import {TASK_TEMPLATES,taskFields,validHrDate} from '@/lib/hrTasks'
export const dynamic='force-dynamic'
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}})
export async function GET(req:Request){try{const s=await currentHr(req);if(!s)return reply({error:'HR sign-in required'},401);const u=new URL(req.url),id=u.searchParams.get('employee');let q=hrDb.from('hr_employees').select('id,company,first_name,last_name,name_display,status,contract_end,next_salary_review').in('company',s.companies);if(id)q=q.eq('id',id);const e=await q;if(e.error)throw e.error;if(id&&!e.data?.length)return reply({error:'Employee unavailable'},404);if(!e.data?.length)return reply({tasks:[],employees:[],has_more:false});let tq=hrDb.from('hr_employee_tasks').select('*').in('employee_id',e.data.map(x=>x.id)).order('due_on',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(!id)tq=tq.eq('status','open');const r=await tq.limit(501);if(r.error)throw r.error;return reply({tasks:(r.data||[]).slice(0,500),employees:e.data,has_more:(r.data?.length||0)>500})}catch(e){return hrError(e)}}
export async function POST(req:Request){try{
 const s=await currentHr(req);if(!s)return reply({error:'HR sign-in required'},401);const b=await req.json();const e=await hrDb.from('hr_employees').select('id').eq('id',b.employee_id).in('company',s.companies).maybeSingle();if(e.error)throw e.error;if(!e.data)return reply({error:'Employee unavailable'},404)
 const actor=s.username,now=new Date().toISOString();let r
 if(b.template){const template=Object.hasOwn(TASK_TEMPLATES,b.template)?TASK_TEMPLATES[b.template]:null;if(!template||(b.due_on&&!validHrDate(b.due_on))||typeof b.owner!=='string'||b.owner.length>100)return reply({error:'Invalid template'},400);const old=await hrDb.from('hr_employee_tasks').select('template_key').eq('employee_id',b.employee_id);if(old.error)throw old.error;const known=new Set((old.data||[]).map(x=>x.template_key));const rows=template.map(([ko,en],i)=>({employee_id:b.employee_id,template_key:b.template+'_'+i,kind:b.template,title:en,title_ko:ko,owner:b.owner.trim(),due_on:b.due_on||null,status:'open',notes:'',actor})).filter(x=>!known.has(x.template_key));if(!rows.length)return reply({ok:true,added:0});r=await hrDb.from('hr_employee_tasks').insert(rows);if(r.error)throw r.error;return reply({ok:true,added:rows.length})
 }else{const fields=taskFields(b);if(b.id){const old=await hrDb.from('hr_employee_tasks').select('id,version,status,completed_at,completed_by').eq('id',b.id).eq('employee_id',b.employee_id).maybeSingle();if(old.error)throw old.error;if(!old.data)return reply({error:'Task unavailable'},404);if(old.data.version!==b.version)return reply({error:'Task changed. Reload before saving.'},409);r=await hrDb.from('hr_employee_tasks').update({...fields,actor,version:b.version+1,updated_at:now,completed_at:fields.status==='done'?(old.data.completed_at||now):null,completed_by:fields.status==='done'?(old.data.completed_by||actor):null}).eq('id',b.id).eq('version',b.version).select('id').maybeSingle();if(!r.error&&!r.data)return reply({error:'Task changed. Reload.'},409)}else r=await hrDb.from('hr_employee_tasks').insert({...fields,employee_id:b.employee_id,actor,completed_at:fields.status==='done'?now:null,completed_by:fields.status==='done'?actor:null});if(r.error)throw r.error}
 return reply({ok:true})
 }catch(e:any){if(e?.code==='23505')return reply({error:'Checklist already added. Reload.'},409);if(e instanceof SyntaxError||e instanceof Error&&e.message.startsWith('Invalid'))return reply({error:e.message},400);return hrError(e)}}

