CREATE TABLE IF NOT EXISTS bookings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reservation_no TEXT UNIQUE,
  status TEXT DEFAULT '접수',
  booker_name TEXT NOT NULL,
  booker_english TEXT DEFAULT '',
  reservation_date DATE DEFAULT CURRENT_DATE,
  balance_date DATE,
  students JSONB DEFAULT '[]',
  accom_type TEXT DEFAULT '',
  accom_room TEXT DEFAULT '',
  accom_weeks INTEGER DEFAULT 2,
  checkin_date DATE,
  checkout_date DATE,
  pickup TEXT DEFAULT 'O',
  drop_off TEXT DEFAULT 'O',
  pickup_place TEXT DEFAULT '',
  flight_in TEXT DEFAULT '',
  flight_out TEXT DEFAULT '',
  house_no TEXT DEFAULT '',
  special_request TEXT DEFAULT '',
  agency TEXT DEFAULT '개인',
  ssp TEXT DEFAULT 'O',
  base_price INTEGER DEFAULT 0,
  billing_items JSONB DEFAULT '[]',
  discounts JSONB DEFAULT '[]',
  locals JSONB DEFAULT '[{"name":"SSP / SSP I card","amount":""},{"name":"드림하우스 보증금","amount":""}]',
  total_discount INTEGER DEFAULT 0,
  final_price INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
