'use client';
import Image from 'next/image';
import Matching from './Matching';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import data from '@/lib/learning/tree-house.json';
import {getDraft,putDraft,initialDraft,normalizeAnswer,type Draft,type Phase,type Section} from '@/lib/learning/storage';
import {Icon,WordArt,InkPad,Recorder,useSpeech} from './Tools';
const meanings=['나무','집','오르다','사다리','똑똑 두드리다','문','정글','창문'];
const explanations=['굵은 줄기 위로 초록 잎이 자라요. 집을 든든하게 받쳐주는 나무예요.','지붕과 벽이 있고, 우리가 안에서 지낼 수 있어요. 나무 위에도 작은 집이 있네요!','손과 발을 써서 위로 올라가요. 바비와 미아는 아빠의 도움을 받아 올라가요.','한 칸씩 밟고 오르내리는 도구예요. 아빠와 함께 천천히 올라가요.','문을 살짝 똑똑! 안에 있는 사람에게 내가 왔다고 알려줘요.','열고 닫으면서 집 안으로 들어가요. 할아버지가 “들어오렴!” 하고 부르세요.','나무와 식물이 빽빽하게 자라는 숲이에요. 이야기 속 정글은 할아버지가 그린 그림이에요.','벽에 나 있어서 바깥을 볼 수 있어요. 창문 너머에는 어떤 그림이 있을까요?'];
const phases:Phase[]=['meet','listen','match','spell','write','speak'];
const phaseNames=['만나요','그림 찾기','짝 맞추기','스펠링','써봐요','말해요'];
const sections:Section[]=['scene','words','story','create','finish'];
const sectionNames=['나무집 탐험','단어랑 놀기','이야기 읽기','내 이야기','모험 기록'];
const spots=[{i:0,x:55,y:76},{i:1,x:52,y:21},{i:3,x:35,y:66},{i:5,x:43,y:39},{i:7,x:60,y:33}];
const paragraphs=[data.story.slice(0,data.story.indexOf('There is a big window.')),data.story.slice(data.story.indexOf('There is a big window.'),data.story.indexOf('Grandpa opens a book.')),data.story.slice(data.story.indexOf('Grandpa opens a book.'))];
export default function Player({startWord,onReturn,storyLine}:{startWord?:number;onReturn?:()=>void;storyLine?:string}={}){
 const [draft,setDraft]=useState<Draft>(initialDraft);const [ready,setReady]=useState(false);const [saveError,setSaveError]=useState('');const [selected,setSelected]=useState(0);const [feedback,setFeedback]=useState('');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [assisted,setAssisted]=useState(false);const {speak,stop,speaking,speechError}=useSpeech();
 useEffect(()=>{let live=true;getDraft().then(d=>{if(live){if(d)setDraft(startWord===undefined?d:{...d,section:'words',index:startWord,phase:'meet'});setReady(true);}}).catch(()=>{if(live){setReady(true);setSaveError('기기 저장소를 열지 못했어요. 지금 한 활동은 다시 열 때 남지 않을 수 있어요.');}});return()=>{live=false;};},[startWord]);
 useEffect(()=>{if(!ready)return;putDraft(draft).then(()=>setSaveError('')).catch(()=>setSaveError('저장하지 못했어요. 브라우저의 저장 공간과 개인정보 보호 설정을 확인해주세요.'));},[draft,ready]);
 const word=data.words[draft.index];const evidence=draft.evidence[word.word]||{};
 function mark(field:Phase,extra={}){setDraft(d=>({...d,evidence:{...d.evidence,[word.word]:{...d.evidence[word.word],[field]:true,...extra}}}));}
 function go(section:Section){if(busy)return;stop();setFeedback('');setDraft(d=>({...d,section}));}
 function phase(p:Phase){if(busy)return;stop();setFeedback('');setAnswer('');setAssisted(false);setDraft(d=>({...d,phase:p}));}
 function next(){if(busy)return;stop();setFeedback('');setAnswer('');setAssisted(false);const p=phases.indexOf(draft.phase);if(p===phases.length-1&&onReturn){onReturn();return;}setDraft(d=>p<phases.length-1?{...d,phase:phases[p+1]}:d.index<7?{...d,index:d.index+1,phase:'meet'}:{...d,section:'story'});}
 function check(){const ok=normalizeAnswer(answer)===word.word;setDraft(d=>({...d,evidence:{...d.evidence,[word.word]:{...d.evidence[word.word],spell:ok||d.evidence[word.word]?.spell,spellAttempts:(d.evidence[word.word]?.spellAttempts||0)+1,...(ok?{spellingSupport:assisted}:{})}}}));if(ok)speak(storyLine||word.example);setFeedback(ok?'맞았어요! 글자들이 제자리를 찾았어요.':'조금 달라요. 소리를 다시 듣고 천천히 해봐요.');}
 if(!ready)return <main className="learn-loading">나무집 문을 열고 있어요…</main>;
 const hidden=draft.phase==='listen'||draft.phase==='spell';
 return <main className={`player ${onReturn?'story-embedded':''}`} >{onReturn&&<button className="story-return" disabled={busy} onClick={()=>{stop();onReturn();}}><Icon name="back"/> 이야기로 돌아가기</button>}{!onReturn&&<><header className="learn-header"><Link href="/learn" className="learn-brand" onClick={e=>{if(busy)e.preventDefault();}}><Icon name="leaf"/> DREAM <span>LEARNING</span></Link><span className="level-pill">BR40 · WEEK 01 · DAY 01</span></header><nav className="journey" aria-label="학습 순서">{sections.map((s,i)=><button key={s} disabled={busy} aria-current={draft.section===s?'step':undefined} onClick={()=>go(s)}><span>{i+1}</span>{sectionNames[i]}</button>)}</nav></>}<div className="storage-line"><span>MY TREE HOUSE</span><span>{saveError?'저장 확인 필요':'학습 기록 · 이 기기에 자동 저장'}</span></div>{saveError&&<p className="error-message" role="alert">{saveError}</p>}{speechError&&<p className="error-message" role="alert">{speechError}</p>}
 {draft.section==='scene'&&<><div className="section-heading"><span className="eyebrow">01 / EXPLORE</span><h1>나무집에 놀러 왔어요!</h1><p>반짝이는 동그라미를 눌러 무엇이 있는지 알아봐요.</p></div><div className="explore-grid"><div className="interactive-scene"><Image src="/learning/tree-house/scene.webp" alt="나무 위 집의 나무, 집, 사다리, 문, 창문을 탐험해요" width={1408} height={1024} priority/>{spots.map(({i,x,y})=><button key={i} style={{left:`${x}%`,top:`${y}%`}} className={`hotspot ${draft.found.includes(i)?'found':''}`} aria-label={`${meanings[i]} 알아보기`} onClick={()=>{setSelected(i);speak(data.words[i].word);setDraft(d=>({...d,found:Array.from(new Set([...d.found,i]))}));}}>{draft.found.includes(i)?<Icon name="check" size={18}/>:'+'}</button>)}<span className="scene-badge">발견한 친구들 {draft.found.length} / 5</span></div><aside className="discovery-card"><span className="eyebrow">HELLO, {data.words[selected].word.toUpperCase()}!</span><WordArt index={selected} label={meanings[selected]}/><h2>{data.words[selected].word} <button className="sound-button" aria-label="선택한 단어 듣기" onClick={()=>speak(data.words[selected].word)}><Icon name="sound"/></button></h2><strong>{meanings[selected]}</strong><p>{explanations[selected]}</p><div className="teacher-bubble">“나무집으로 올라가기 전에,<br/>8개의 단어 친구를 만나볼까요?”</div></aside></div><div className="section-footer"><p>바비와 미아의 모험이 시작돼요.</p><button className="primary" onClick={()=>go('words')}>단어 친구 만나기 <Icon name="arrow"/></button></div></>}
 {draft.section==='words'&&<><div className="section-heading compact"><span className="eyebrow">02 / WORD PLAY</span><h1>{onReturn?"이야기에서 만난 친구":"단어 하나, 모험 하나."}</h1>{storyLine?<button className="story-context" disabled={busy} onClick={()=>speak(storyLine)}><Icon name="sound"/>{storyLine}</button>:<p>{draft.index+1} / 8번째 단어 · 짧게 여러 번 만나면 더 잘 기억해요.</p>}</div><div className="word-dots">{data.words.map((w,i)=><button disabled={busy} key={w.word} aria-label={`${i+1}번째 단어`} aria-current={i===draft.index?'true':undefined} onClick={()=>{stop();setAnswer('');setFeedback('');setAssisted(false);setDraft(d=>({...d,index:i,phase:'meet'}));}}>{hidden?i+1:w.word}{draft.evidence[w.word]?.spell&&<Icon name="check" size={13}/>}</button>)}</div><div className="activity-card"><nav className="phase-nav" aria-label="단어 활동">{phases.map((p,i)=><button key={p} disabled={busy} aria-current={draft.phase===p?'step':undefined} onClick={()=>phase(p)}>{phaseNames[i]}{evidence[p]&&<Icon name="check" size={14}/>}</button>)}</nav>
 {draft.phase==='meet'&&<div className="meet-grid"><WordArt index={draft.index} label={meanings[draft.index]}/><div><span className="eyebrow">우리 나무집의 단어 친구</span><h2 className="big-word">{word.word}</h2><span className="meaning">{meanings[draft.index]} <small>{word.ipa}</small></span><p>{explanations[draft.index]}</p><button className="primary" onClick={()=>{speak(word.word);mark('meet');}}><Icon name="sound"/> 단어 듣기</button><button className="example" onClick={()=>speak(word.example)}><Icon name="sound"/>{word.example}</button><p className="english-definition">{word.definition}</p></div></div>}
 {draft.phase==='match'&&<Matching key={word.word} index={draft.index} onComplete={()=>mark('match')}/>}
 {draft.phase==='listen'&&<div className="game-area"><span className="activity-icon"><Icon name="sound" size={28}/></span><h2>듣고, 그림을 찾아요.</h2><p>어떤 단어가 들리나요? 맞는 그림을 톡!</p><button className="primary" onClick={()=>speak(word.word)}><Icon name="sound"/> 단어 소리 듣기</button><div className="picture-choices">{[draft.index,(draft.index+3)%8,(draft.index+5)%8].sort((a,b)=>a-b).map((n,i)=><button key={n} aria-label={`그림 ${i+1}`} onClick={()=>{const ok=n===draft.index;setDraft(d=>({...d,evidence:{...d.evidence,[word.word]:{...d.evidence[word.word],listen:ok||d.evidence[word.word]?.listen,listenAttempts:(d.evidence[word.word]?.listenAttempts||0)+1}}}));setFeedback(ok?'찾았어요! 귀 기울여 잘 들었네요.':'다시 들어볼까요? 그림을 천천히 살펴봐요.');}}><WordArt index={n} label={`선택 그림 ${i+1}`}/><span>{i+1}</span></button>)}</div></div>}
 {draft.phase==='spell'&&<div className="game-area spelling"><div className="spell-picture"><WordArt index={draft.index} label="스펠링을 맞힐 그림"/></div><h2>글자들을 모아볼까요?</h2><button className="text-button" onClick={()=>speak(word.word)}><Icon name="sound"/> 소리 다시 듣기</button><form onSubmit={e=>{e.preventDefault();check();}}><label htmlFor="spelling">키보드로 쓰거나 아래 글자를 눌러요.</label><input id="spelling" autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={24} value={answer} onChange={e=>setAnswer(e.target.value)}/><div className="letter-tiles">{word.word.split('').map((c,i)=>({c,i})).sort((a,b)=>a.c.localeCompare(b.c)||b.i-a.i).map(({c,i})=><button type="button" key={i} aria-label={`${c} 글자 넣기`} onClick={()=>{setAnswer(a=>(a+c).slice(0,24));setAssisted(true);}}>{c}</button>)}<button type="button" aria-label="마지막 글자 지우기" onClick={()=>setAnswer(a=>a.slice(0,-1))}><Icon name="undo"/></button></div><button className="primary" type="submit" disabled={!answer.trim()}>맞는지 볼까요? <Icon name="check"/></button></form></div>}
 {draft.phase==='write'&&<div className="writing-area"><h2>{word.word}, 내 손으로 써봐요.</h2><p>직접 써도 좋고, 연한 글자를 따라 써도 좋아요.</p><InkPad key={word.word} value={draft.ink[word.word]||[]} guide={word.word} label={word.word} onChange={ink=>setDraft(d=>({...d,ink:{...d.ink,[word.word]:ink},evidence:{...d.evidence,[word.word]:{...d.evidence[word.word],write:ink.length>0}}}))}/><label className="typing-label">키보드로도 쓸 수 있어요<input value={draft.typed[word.word]||''} maxLength={100} onChange={e=>{const val=e.target.value;setDraft(d=>({...d,typed:{...d.typed,[word.word]:val}}));}} placeholder={word.word}/></label><small>손글씨는 그대로 보관해요. 글자 모양을 자동으로 채점하지 않아요.</small></div>}
 {draft.phase==='speak'&&<div className="game-area"><span className="eyebrow">나무집에 내 목소리를 들려줘요</span><h2 className="big-word">{word.word}</h2><button className="example" disabled={busy} onClick={()=>speak(word.example)}><Icon name="sound"/>{word.example}</button><p>단어를 말하고, 여유가 있으면 문장도 읽어봐요.</p><Recorder key={word.word} recordingKey={`word-${word.word}`} text={`${word.word}. ${word.example}`} onBusy={setBusy} onSaved={()=>mark('speak')}/></div>}
 {feedback&&<p className="feedback" role="status">{feedback}</p>}<div className="activity-footer"><span>{evidence[draft.phase]?'이 활동을 해봤어요!':'어려우면 다음에 다시 해도 괜찮아요.'}</span><button className="primary" disabled={busy} onClick={next}>{draft.phase==='speak'?(onReturn?'이야기 계속하기':draft.index===7?'이야기로 가기':'다음 단어'):'다음 활동'}<Icon name="arrow"/></button></div></div></>}
 {draft.section==='story'&&<><div className="section-heading"><span className="eyebrow">03 / STORY TIME</span><h1>A Place to Read</h1><p>할아버지의 나무집에는 어떤 비밀이 있을까요?</p></div><div className="story-cover"><Image src="/learning/tree-house/scene.webp" alt="바비와 미아가 찾아가는 나무집" width={1408} height={1024}/><div><span>MY TREE HOUSE</span><h2>책을 읽는<br/>우리만의 작은 집</h2><button className="primary" disabled={busy} onClick={()=>speaking?stop():speak(data.story)}><Icon name={speaking?'stop':'sound'}/>{speaking?'듣기 멈추기':'이야기 전체 듣기'}</button></div></div><div className="story-pages">{paragraphs.map((p,i)=><article key={i}><div className="story-illustration" role="img" aria-label={["아빠가 사다리를 오르는 바비를 도와주고 미아가 기다려요","할아버지가 아이들에게 정글 그림을 보여줘요","할아버지와 바비, 미아가 함께 책을 읽어요"][i]}><Image src="/learning/tree-house/story.webp" alt="" width={2172} height={724} sizes="1200px" style={{width:"300%",maxWidth:"none",height:"100%",position:"absolute",left:`${-i*100}%`}}/></div><div className="story-page-top"><span>SCENE 0{i+1} · {['나무집으로 올라가요','창문 너머의 비밀','함께 책을 읽어요'][i]}</span><button disabled={busy} className="sound-button" aria-label={`${i+1}번째 장면 듣기`} onClick={()=>speak(p)}><Icon name="sound"/></button></div><p>{p.split(/(\b(?:tree|house|climb|ladder|knock|door|jungle|window)\b)/gi).map((part,j)=>data.words.some(w=>w.word===part.toLowerCase())?<button disabled={busy} className="story-word" key={j} onClick={()=>speak(part)}>{part}</button>:<span key={j}>{part}</span>)}</p></article>)}</div><div className="story-check"><h2>이야기 속에서 찾아봐요</h2>{data.questions.map((q,i)=><fieldset key={q}><legend>{q}</legend>{(i===0?['Dad.','Mia.','Bobby.']:['A real jungle.','A painted picture of a jungle.','A tall ladder.']).map((a,j)=><button className={draft.storyAnswers[i]===j?'chosen':''} key={a} onClick={()=>setDraft(d=>({...d,storyAnswers:{...d.storyAnswers,[i]:j}}))}>{a}</button>)}{draft.storyAnswers[i]!==undefined&&<p role="status">{draft.storyAnswers[i]===(i===0?0:1)?'맞아요! 이야기를 잘 따라왔어요.':'이야기를 다시 살펴볼까요?'}</p>}</fieldset>)}<label className="read-check"><input type="checkbox" checked={draft.storyRead} onChange={e=>setDraft(d=>({...d,storyRead:e.target.checked}))}/> 이야기를 끝까지 읽었어요.</label><h3>좋아하는 문장을 내 목소리로</h3><p>“I like this little house,” says Bobby.</p><Recorder recordingKey="story-favorite" text='I like this little house.' onBusy={setBusy}/></div><div className="section-footer"><p>이제, 나만의 나무집 이야기를 써볼까요?</p><button className="primary" disabled={busy} onClick={()=>go('create')}>내 이야기 만들기 <Icon name="arrow"/></button></div></>}
 {draft.section==='create'&&<><div className="section-heading"><span className="eyebrow">04 / MY LITTLE STORY</span><h1>내 나무집에는 무엇이 있나요?</h1><p>오늘 배운 단어로 나만의 한 문장을 만들어요.</p></div><div className="create-card"><div className="sentence-starters">{data.frames.map(f=><button key={f} onClick={()=>setDraft(d=>({...d,sentence:f.replace('...',''),created:false}))}>{f}</button>)}</div><label htmlFor="my-story">내가 만든 영어 문장</label><textarea id="my-story" maxLength={500} rows={3} placeholder="My tree house has a window." value={draft.sentence} onChange={e=>setDraft(d=>({...d,sentence:e.target.value,created:false}))}/><div className="word-bank">{data.words.map(w=><button key={w.word} onClick={()=>setDraft(d=>({...d,sentence:(d.sentence.trimEnd()+' '+w.word).trim().slice(0,500),created:false}))}>{w.word}</button>)}</div><InkPad value={draft.ink.myStory||[]} label="내 이야기" onChange={ink=>setDraft(d=>({...d,ink:{...d.ink,myStory:ink}}))}/><p>나무집 그림을 그리거나 문장을 손으로 써도 좋아요.</p><Recorder recordingKey="my-story" text={draft.sentence} onBusy={setBusy}/><button className="primary" disabled={busy||(!draft.sentence.trim()&&!draft.ink.myStory?.length)} onClick={()=>{setDraft(d=>({...d,created:true,section:'finish'}));stop();}}>내 이야기 간직하기 <Icon name="star"/></button></div></>}
 {draft.section==='finish'&&<><div className="section-heading"><span className="finish-star"><Icon name="star" size={40}/></span><span className="eyebrow">MY ADVENTURE COLLECTION</span><h1>오늘의 모험이 여기 남았어요.</h1><p>다 못했어도 괜찮아요. 언제든 이어서 놀 수 있어요.</p></div><div className="summary-grid">{[['그림 찾기',Object.values(draft.evidence).filter(e=>e.listen).length],['스펠링 맞히기',Object.values(draft.evidence).filter(e=>e.spell).length],['손글씨 쓰기',Object.values(draft.evidence).filter(e=>e.write).length],['목소리 남기기',Object.values(draft.evidence).filter(e=>e.speak).length]].map(([t,n])=><div key={t}><strong>{n}<small> / 8</small></strong><span>{t}</span></div>)}</div><div className="collection">{data.words.map((w,i)=><button key={w.word} onClick={()=>{setDraft(d=>({...d,section:'words',index:i,phase:'meet'}));setFeedback('');}}><WordArt index={i} label={meanings[i]}/><strong>{w.word}</strong><small>{draft.evidence[w.word]?.spell?(draft.evidence[w.word]?.spellingSupport?'글자 도움으로 성공':'직접 입력 성공'):'다시 만나볼까요?'}</small></button>)}</div>{draft.created&&<div className="saved-story"><span className="eyebrow">내가 만든 이야기</span><h2>{draft.sentence||'손으로 그린 나의 나무집'}</h2><button className="text-button" onClick={()=>go('create')}>글씨와 녹음 다시 보기 <Icon name="arrow"/></button></div>}<div className="section-footer"><Link className="secondary" href="/learn">학습 홈</Link><button className="primary" onClick={()=>go('scene')}>나무집 다시 탐험하기 <Icon name="leaf"/></button></div></>}
 <footer className="learn-bottom">DREAM ACADEMY · 작은 한 걸음도 소중한 배움이에요.</footer></main>;
}
