'use client'
import {useState,useEffect,useCallback} from 'react'
import {TASK_KINDS} from '@/lib/hrTasks'
import {displayName} from '@/lib/hr'
import {HR_COMPANY_SLUGS} from '@/lib/hrAccess'
type Props={request:(url:string,init?:RequestInit)=>Promise<any>;language:'ko'|'en';employeeId?:string;company?:string;onDirty?:(v:boolean)=>void}
const blank=()=>({id:'',title:'',title_ko:'',kind:'other',owner:'',due_on:'',status:'open',notes:'',version:0})
export default function HrTasks({request,language,employeeId,company,onDirty}:Props){
 const t=(ko:string,en:string)=>language==='ko'?ko:en
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[form,setForm]=useState(blank),[dirty,setDirty]=useState(false),[filter,setFilter]=useState('open')
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'}),cutoff=new Date(Date.now()+30*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Manila'})
 const load=useCallback(async()=>{setError('');try{setData(await request('/api/hr/tasks'+(employeeId?'?employee='+employeeId:'')))}catch(e){setError((e as Error).message)}},[request,employeeId])
 useEffect(()=>{void load()},[load]);useEffect(()=>{onDirty?.(dirty);return()=>onDirty?.(false)},[dirty,onDirty])
 const save=async(template?:string)=>{setBusy(true);setError('');setNotice('');try{const r=await request('/api/hr/tasks',{method:'POST',body:JSON.stringify(template?{employee_id:employeeId,template,owner:form.owner,due_on:form.due_on}:{...form,employee_id:employeeId})});setDirty(false);setForm(blank());await load();setNotice(template&&r.added===0?t('이미 등록된 체크리스트입니다.','This checklist already exists.'):t('저장되었습니다.','Saved.'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const edit=(task:any)=>{if(dirty&&!confirm(t('입력 중인 내용을 버릴까요?','Discard unsaved changes?')))return;setForm({...task,due_on:task.due_on||''});setDirty(false);setNotice('')}
 const change=(key:string,value:string)=>{setForm(old=>({...old,[key]:value}));setDirty(true);setNotice('')}
 const employeeMap=new Map<string,any>((data?.employees||[]).map((e:any)=>[e.id,e]));const tasks=(data?.tasks||[]).filter((r:any)=>!company||employeeMap.get(r.employee_id)?.company===company)
 const open=tasks.filter((r:any)=>r.status==='open'),visible=tasks.filter((r:any)=>filter==='all'||r.status===filter)
 const dates=(data?.employees||[]).filter((e:any)=>e.status==='Active'&&(!company||e.company===company)).flatMap((e:any)=>['contract_end','next_salary_review'].filter(k=>e[k]&&e[k]<=cutoff).map(k=>({employee:e,date:e[k],kind:k}))).sort((a:any,b:any)=>a.date.localeCompare(b.date))
 const url=(id:string)=>'/admin/HR/companies/'+HR_COMPANY_SLUGS[employeeMap.get(id)?.company]+'/employees/'+id+'?section=tasks'
 return <section className="hr-card hr-operations"><div className="hr-card-heading"><div><p className="hr-eyebrow">HR ACTION CENTER</p><h2>{employeeId?t('입사·퇴사·후속 업무','Employee lifecycle & follow-ups'):t('HR 확인할 일','HR action center')}</h2><p className="hr-muted">{t('담당자와 마감일을 정하고 처리 결과를 남깁니다. 완료 처리는 실제 계약·계정·급여를 자동 변경하지 않습니다.','Assign owners and deadlines, then record outcomes. Completing a checklist does not automatically change contracts, account access or payroll.')}</p></div><button type="button" className="hr-btn" disabled={busy} onClick={()=>void load()}>{t('새로고침','Refresh')}</button></div>
 {error&&<p role="alert" className="hr-alert">{error}</p>}{notice&&<p role="status" className="hr-success">{notice}</p>}
 {!data&&!error?<p>{t('불러오는 중…','Loading…')}</p>:<><div className="hr-stats"><div><small>{t('미완료','Open')}</small><strong>{open.length}</strong></div><div><small>{t('기한 경과','Overdue')}</small><strong>{open.filter((r:any)=>r.due_on&&r.due_on<today).length}</strong></div><div><small>{t('담당자 미지정','Unassigned')}</small><strong>{open.filter((r:any)=>!r.owner).length}</strong></div><div><small>{t('계약·급여 검토 예정/경과','Contract / pay reviews due')}</small><strong>{dates.length}</strong></div></div>
 {dates.length>0&&<div className="hr-operation-alerts">{dates.map((r:any)=><a className={r.date<today?'overdue':''} key={r.employee.id+r.kind} href={'/admin/HR/companies/'+HR_COMPANY_SLUGS[r.employee.company]+'/employees/'+r.employee.id+'?section=employment'}><strong>{r.date}</strong> · {displayName(r.employee)} · {r.kind==='contract_end'?t('계약 종료일 확인','Check contract end date'):t('급여 검토','Pay review')}{r.date<today?' · '+t('기한 경과','Overdue'):''}</a>)}</div>}
 {employeeId&&<><div className="hr-task-template"><strong>{t('기본 체크리스트','Starter checklists')}</strong><p>{t('입사·퇴사 체크리스트는 각각 한 번 추가됩니다. 담당자·마감일을 아래에 먼저 입력하면 함께 적용됩니다. 직원별로 각 업무를 수정하거나 미해당으로 처리하세요.','Each starter checklist can be added once. Enter an owner and deadline below to apply them to the checklist. Edit individual tasks or mark them not applicable.')}</p>{['onboarding','offboarding'].map(k=><button type="button" className="hr-btn" key={k} disabled={busy||dirty&&!!form.title} onClick={()=>void save(k)}>+ {TASK_KINDS[k][language==='ko'?0:1]}</button>)}</div>
 <form className="hr-task-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>{form.id?t('업무 수정','Edit task'):t('직접 업무 추가','Add a task')}</h3><div className="hr-field-grid"><label>{t('영문 제목','English title')} *<input required maxLength={180} value={form.title} onChange={e=>change('title',e.target.value)}/></label><label>{t('한글 제목 (선택)','Korean title (optional)')}<input maxLength={180} value={form.title_ko} onChange={e=>change('title_ko',e.target.value)}/></label><label>{t('분류','Category')}<select value={form.kind} onChange={e=>change('kind',e.target.value)}>{Object.entries(TASK_KINDS).map(([k,v])=><option key={k} value={k}>{v[language==='ko'?0:1]}</option>)}</select></label><label>{t('담당자 이름','Owner name')}<input maxLength={100} value={form.owner} onChange={e=>change('owner',e.target.value)} placeholder="Abby / Bella / Manager"/></label><label>{t('마감일','Due date')}<input type="date" value={form.due_on} onChange={e=>change('due_on',e.target.value)}/></label><label>{t('상태','Status')}<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="open">{t('미완료','Open')}</option><option value="done">{t('완료','Done')}</option><option value="cancelled">{t('미해당·취소','Not applicable / cancelled')}</option></select></label></div><label>{t('처리 내용·결과','Notes & outcome')}<textarea maxLength={4000} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label><div className="hr-pay-actions"><button className="hr-btn primary" disabled={busy}>{t('업무 저장','Save task')}</button>{form.id&&<button className="hr-btn" type="button" onClick={()=>{if(!dirty||confirm(t('변경 내용을 취소할까요?','Discard changes?'))){setForm(blank());setDirty(false)}}}>{t('편집 취소','Cancel editing')}</button>}</div></form></>}
 {employeeId&&<label>{t('업무 보기','Show tasks')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">{t('미완료','Open')}</option><option value="done">{t('완료','Done')}</option><option value="cancelled">{t('미해당·취소','Not applicable / cancelled')}</option><option value="all">{t('전체','All')}</option></select></label>}
 <div className="hr-operation-list">{visible.map((r:any)=><article key={r.id} className={r.status==='open'&&r.due_on&&r.due_on<today?'overdue':''}><div><small>{TASK_KINDS[r.kind]?.[language==='ko'?0:1]} · {r.due_on||t('마감 미지정','No deadline')} · {r.owner||t('담당 미지정','Unassigned')}</small><h3>{language==='ko'?r.title_ko||r.title:r.title}</h3>{!employeeId&&<p>{displayName(employeeMap.get(r.employee_id)||{})}</p>}{employeeId&&<p>{r.notes}</p>}{r.completed_at&&<small>{t('완료','Completed')}: {r.completed_at.slice(0,10)} · {r.completed_by}</small>}</div>{employeeId?<button type="button" className="hr-btn" onClick={()=>edit(r)}>{t('수정·완료','Edit / complete')}</button>:<a className="hr-btn" href={url(r.employee_id)}>{t('직원 업무 열기','Open employee tasks')} →</a>}</article>)}</div>{!visible.length&&<p className="hr-muted">{t('이 상태의 업무가 없습니다. 직원 상세에서 입사·퇴사 체크리스트나 후속 업무를 등록하세요.','No tasks in this view. Add a checklist or follow-up task from an employee profile.')}</p>}{data?.has_more&&<p>{t('최대 500건까지 표시됩니다. 직원별 상세에서 확인하세요.','Showing up to 500 tasks. Open individual profiles for more detail.')}</p>}</>}
 </section>
}

