'use client'
import {useState} from 'react'
import {COMPANY_EN} from '@/lib/hrFields'
type Letter={company:string;language:'ko'|'en';number:string;date:string;title:string;to:string;from:string;body:string;prepared:string;approver:string;attachments:string}
const dateToday=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'})
function example(company:string,language:'ko'|'en',kind:string):Letter {
 const ko=language==='ko'
 return {company,language,number:'',date:dateToday(),title:kind==='records'?(ko?'직원 인적사항 등록 및 신분 확인 서류 제출 안내':'Employee Personal Information Registration and Identity Documents'):kind==='meeting'?(ko?'직원 회의 안내':'Staff Meeting Notice'):kind==='training'?(ko?'직원 교육 안내':'Staff Training Notice'):'',to:ko?'전 직원':'All employees',from:ko?'드림컴퍼니 인사팀':'Dream Company – Human Resources Department',body:kind==='records'?(ko?'직원 인사기록을 정비하기 위해 아래 서류의 작성 및 제출을 요청드립니다.\n\n제출 서류\n1. 인사기록카드의 필수 항목을 작성해 주세요.\n2. 유효한 정부발행 신분증 앞·뒷면 사본을 준비해 주세요.\n3. 서명 제출 여부와 방법은 담당 매니저의 안내를 확인해 주세요.\n\n제출 안내\n제출 기한: [날짜와 시간 입력]\n제출처: [담당 매니저와 제출 방법 입력]\n문의: [담당자와 연락처 입력]\n\n개인정보 처리 안내는 회사에서 확인한 내용을 기재해 주세요.':'Please complete and submit the documents below to update your personnel record.\n\nDocuments to submit\n1. Complete the required fields of the Personnel Record Card.\n2. Prepare copies of the front and back of a valid government-issued ID.\n3. Follow your manager’s instructions regarding signature requirements.\n\nSubmission details\nDeadline: [Enter date and time]\nSubmit to: [Enter manager and submission method]\nQuestions: [Enter contact person and details]\n\nInsert the company-approved privacy notice here.') :kind==='meeting'||kind==='training'?(ko?'목적: [내용 입력]\n일시: [날짜와 시간 입력]\n장소: [장소 입력]\n대상: [참석 대상 입력]\n준비 사항: [내용 입력]\n문의: [담당자 입력]':'Purpose: [Enter purpose]\nDate and time: [Enter date and time]\nVenue: [Enter venue]\nParticipants: [Enter participants]\nPreparation: [Enter details]\nContact: [Enter contact person]'):'',prepared:'',approver:'',attachments:''}
}
export default function LetterWorkspace({companies,language,onDirty}:{companies:string[];language:'ko'|'en';onDirty:(v:boolean)=>void}) {
 const t=(ko:string,en:string)=>language==='ko'?ko:en
 const [letter,setLetter]=useState<Letter>(()=>example(companies[0]||'',language,'records'))
 const [kind,setKind]=useState('records'),[changed,setChanged]=useState(false),[message,setMessage]=useState('')
 const update=(key:keyof Letter,value:string)=>{setLetter(old=>({...old,[key]:value}));setChanged(true);onDirty(true);setMessage('')}
 function loadTemplate(next:string,lang=letter.language){if(changed&&!confirm(t('작성 중인 내용을 새 양식으로 바꿀까요?','Replace your current draft with this template?')))return;setKind(next);setLetter(example(letter.company,lang,next));setChanged(false);onDirty(false);setMessage('')}
 function download(){const blob=new Blob([JSON.stringify({format:'dream-hr-letter-v1',letter},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Dream-HR-draft-${letter.date}.json`;a.click();URL.revokeObjectURL(url);setChanged(false);onDirty(false);setMessage(t('초안 파일을 다운로드했습니다. 다른 기기에서도 초안 불러오기로 이어서 작성할 수 있습니다.','Draft downloaded. Use Open draft to continue editing on another device.'))}
 async function importDraft(file?:File){if(!file)return;try{if(file.size>200000)throw Error();const data=JSON.parse(await file.text());const keys=Object.keys(letter) as (keyof Letter)[];if(data.format!=='dream-hr-letter-v1'||!keys.every(k=>typeof data.letter?.[k]==='string'&&data.letter[k].length<=20000)||!companies.includes(data.letter.company)||!['ko','en'].includes(data.letter.language)||!/^\d{4}-\d{2}-\d{2}$/.test(data.letter.date))throw Error();if(changed&&!confirm(t('현재 작성 중인 내용을 바꿀까요?','Replace your current draft?')))return;setLetter(Object.fromEntries(keys.map(k=>[k,data.letter[k]])) as Letter);setChanged(false);onDirty(false);setMessage(t('초안을 불러왔습니다.','Draft opened.'))}catch{setMessage(t('초안 형식이나 회사 접근 권한을 확인해 주세요.','Check the draft format and your company access.'))}}
 const ko=letter.language==='ko'
 const fields:[keyof Letter,string,string][]=[['number','문서번호','Document number'],['date','발행일','Issue date'],['title','제목','Subject'],['to','수신','To'],['from','발신','From'],['prepared','작성 담당자 / 직책','Prepared by / title'],['approver','승인 담당자 / 직책','Approver / title'],['attachments','붙임 목록','Attachments']]
 const formattedDate=/^\d{4}-\d{2}-\d{2}$/.test(letter.date)?new Date(letter.date+'T12:00:00').toLocaleDateString(ko?'ko-KR':'en-US',{year:'numeric',month:'long',day:'numeric',weekday:'long'}):''
 return <section className="hr-letters"><div className="hr-page-heading hr-no-print"><div><p className="hr-eyebrow">DOCUMENT STUDIO</p><h1>{t('공문 작성','Official letters')}</h1><p>{t('양식을 선택하고 내용을 채우면 같은 형식의 공문이 완성됩니다.','Choose a template and fill in the details to create a consistent company letter.')}</p></div><div className="hr-inline"><button className="hr-btn" onClick={download}>{t('초안 다운로드','Download draft')}</button><label className="hr-btn">{t('초안 불러오기','Open draft')}<input type="file" accept=".json" style={{display:'none'}} onChange={e=>{void importDraft(e.target.files?.[0]);e.target.value=''}}/></label><button className="hr-btn primary" onClick={()=>{if(!letter.title.trim()||!letter.to.trim()||!letter.body.trim()){setMessage(t('제목, 수신, 본문을 입력해 주세요.','Enter a subject, recipient and body.'));return}window.print()}}>{t('인쇄 / PDF 저장','Print / Save PDF')}</button></div></div>
 {message&&<div className="hr-success hr-no-print" role="status">{message}</div>}
 <div className="hr-letter-layout"><div className="hr-card hr-no-print"><h2>{t('공문 내용','Letter details')}</h2><p className="hr-help">{t('초안은 자동으로 서버에 저장되지 않습니다. 작업 후 초안 파일을 보관해 주세요.','Drafts are not saved to the server automatically. Download a draft to keep your work.')}</p><label>{t('템플릿','Template')}<select value={kind} onChange={e=>loadTemplate(e.target.value)}><option value="records">{t('직원 인적사항 제출 안내','Personnel records request')}</option><option value="meeting">{t('직원 회의 안내','Staff meeting')}</option><option value="training">{t('교육 안내','Training notice')}</option><option value="blank">{t('일반 공문','General letter')}</option></select></label><label>{t('문서 언어','Document language')}<select value={letter.language} onChange={e=>loadTemplate(kind,e.target.value as 'ko'|'en')}><option value="ko">한국어</option><option value="en">English</option></select></label><p className="hr-help">{t('언어를 바꾸면 해당 언어의 기본 예시를 새로 불러옵니다. 작성한 내용의 자동 번역은 아닙니다.','Changing language loads a fresh template in that language; it does not translate custom text.')}</p><label>{t('발행 회사','Issuing company')}<select value={letter.company} onChange={e=>update('company',e.target.value)}>{companies.map(c=><option key={c} value={c}>{language==='ko'?c:COMPANY_EN[c]||c}</option>)}</select></label>{fields.map(([key,k,e])=><label key={key}>{t(k,e)}<input type={key==='date'?'date':'text'} maxLength={500} value={letter[key]} onChange={ev=>update(key,ev.target.value)}/></label>)}<label>{t('본문','Body')}<textarea rows={18} maxLength={20000} value={letter.body} onChange={e=>update('body',e.target.value)}/></label><p className="hr-help">{t('서명란은 빈칸으로 출력됩니다. 담당자 이름을 넣는 것만으로 승인되거나 발송되지 않습니다.','Signature lines remain blank. Adding an approver’s name does not approve or send this letter.')}</p></div>
 <article className="hr-letter-paper" lang={letter.language}><header><strong>DREAM COMPANY</strong><b>{COMPANY_EN[letter.company]||letter.company}</b><span>Lapu-Lapu City (Mactan), Cebu, Philippines</span></header><div className="hr-letter-meta"><span>{ko?'문서번호':'Doc. No.'}: {letter.number||'________________'}</span><span>{formattedDate}</span></div><h1>{letter.title|| (ko?'공문 제목':'Letter subject')}</h1><dl><div><dt>{ko?'수신':'To'}</dt><dd>{letter.to}</dd></div><div><dt>{ko?'발신':'From'}</dt><dd>{letter.from}</dd></div></dl><div className="hr-letter-body">{letter.body}</div>{letter.attachments&&<p className="hr-letter-attachments">{ko?'붙임':'Attachments'}: {letter.attachments}</p>}<footer><div><b>{ko?'발신 / 담당':'Prepared by'}</b><div className="hr-signature-line"/><p>{letter.prepared}</p></div><div><b>{ko?'승인':'Approved by'}</b><div className="hr-signature-line"/><p>{letter.approver}</p></div></footer></article></div></section>
}
