'use client'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import { displayName, HR_REQUIREMENTS, type HrEmployee } from '@/lib/hr'
import { HR_COMPANY_SLUGS } from '@/lib/hrAccess'
import { COMPANY_EN, HR_SECTIONS, REQUIREMENT_KO, VALUE_KO, type Lang, type Field } from '@/lib/hrFields'
import './hr.css'
import LetterWorkspace from './LetterWorkspace'

type User = { username: string; name?: string; role: string; companies: string[]; language?: Lang; full?: boolean; must_change_pw?: boolean }
type Session = { token: string; user: User }
type RecordEntry = { id: string; kind: string; title: string; content: string; occurred_on: string; follow_up_on?: string; created_by: string; created_at: string }
const ROOT = '/admin/HR'
const kindLabels: Record<string, [string,string]> = {note:['인사 메모','HR note'],evaluation:['평가','Evaluation'],training:['교육·온보딩','Training / onboarding'],meeting:['면담','Meeting']}
const today = () => new Date().toLocaleDateString('en-CA', {timeZone:'Asia/Manila'})
const asError = (e: unknown) => e instanceof Error ? e.message : String(e)
const docCount = (e: HrEmployee) => HR_REQUIREMENTS.filter(r => e.requirements?.[r.key]).length
function initialSession(): Session | null { try { return JSON.parse(localStorage.getItem('hrSession') || 'null') } catch { return null } }
function companyPath(co: string) { return `${ROOT}/companies/${HR_COMPANY_SLUGS[co]}` }

export default function HRPage() {
 const router = useRouter(), pathname = usePathname()
 const [session,setSession] = useState<Session|null|undefined>(undefined)
 const [lang,setLang] = useState<Lang>('en'), [list,setList] = useState<HrEmployee[]>([])
 const [employee,setEmployee] = useState<HrEmployee|null>(null), [draft,setDraft] = useState<HrEmployee|null>(null)
 const [records,setRecords] = useState<RecordEntry[]>([]), [recordError,setRecordError] = useState('')
 const [loading,setLoading] = useState(true), [detailLoading,setDetailLoading] = useState(false), [error,setError] = useState(''), [success,setSuccess] = useState('')
 const [editing,setEditing] = useState(false), [busy,setBusy] = useState(false), [tab,setTab] = useState('overview')
 const [query,setQuery] = useState(''), [status,setStatus] = useState('all'), [department,setDepartment] = useState('all'), [attention,setAttention] = useState(false)
 const parts = pathname.slice(ROOT.length).split('/').filter(Boolean)
 const company = Object.keys(HR_COMPANY_SLUGS).find(c => HR_COMPANY_SLUGS[c] === parts[1])
 const employeeId = parts[2] === 'employees' ? parts[3] : undefined
 const isNew = employeeId === 'new', accountPage = parts[0] === 'account', lettersPage = parts[0] === 'letters'
 const t = useCallback((ko: string,en: string) => lang === 'ko' ? ko : en,[lang])
 const valueLabel = (v?: string) => !v ? '—' : lang === 'ko' ? VALUE_KO[v] || v : COMPANY_EN[v] || v
 const companyLabel = (v: string) => lang === 'ko' ? v : COMPANY_EN[v] || v
 const dirty = !!draft && JSON.stringify(draft) !== JSON.stringify(employee)
 const [recordDirty,setRecordDirty] = useState(false)
 useEffect(() => { const s = initialSession(); setSession(s); setLang(s?.user.username === 'may' ? 'ko' : 'en'); if (!s) setLoading(false) },[])
 useEffect(() => { if (!dirty && !recordDirty) return; const fn = (e: BeforeUnloadEvent) => {e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn) },[dirty,recordDirty])
 const request = useCallback(async (url: string,init?: RequestInit) => {
  const response = await fetch(url,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.token}`,...init?.headers},cache:'no-store'})
  const result = await response.json()
  if (!response.ok) { if(response.status === 401){localStorage.removeItem('hrSession');setSession(null)};throw new Error(result.error || 'Request failed / 요청 실패') }
  return result
 },[session?.token])
 const refresh = useCallback(async () => {
  setLoading(true);setError('')
  try {const data = await request('/api/hr/employees');setList(data.employees);setSession(s=>s?{...s,user:data.user}:s);setLang(data.user.language)}catch(e){setError(asError(e))}finally{setLoading(false)}
 },[request])
 useEffect(()=>{if(session?.token)void refresh()},[session?.token,refresh])
 useEffect(()=>{
  setSuccess('');setTab('overview');setEmployee(null);setDraft(null);setRecords([]);setRecordError('');setEditing(isNew);setRecordDirty(false)
  if (!session?.token || !employeeId || !company) return
  if(isNew){const blank:HrEmployee={id:'',company,status:'Active',nationality:'Filipino',salary_type:'Monthly',cost_center:company};setEmployee(blank);setDraft(blank);setTab('personal');return}
  let active=true;setDetailLoading(true);setError('')
  request('/api/hr/employees?id='+encodeURIComponent(employeeId)).then(data=>{if(active){const emp=data.employees[0];if(emp.company!==company){setError('Employee belongs to another company. / 직원의 소속 회사가 다릅니다.');return}setEmployee(emp);setDraft(emp)}}).catch(e=>{if(active)setError(asError(e))}).finally(()=>{if(active)setDetailLoading(false)})
  request('/api/hr/records?employee='+encodeURIComponent(employeeId)).then(data=>{if(active)setRecords(data.records)}).catch(e=>{if(active)setRecordError(asError(e))})
  return()=>{active=false}
 },[employeeId,company,isNew,session?.token,request])
 function navigate(url: string) { if((dirty||recordDirty)&&!window.confirm(t('저장하지 않은 내용이 있습니다. 이동할까요?','You have unsaved changes. Leave this page?')))return; setEditing(false);setDraft(null);setEmployee(null);setRecordDirty(false);setQuery('');setStatus('all');setDepartment('all');setAttention(false);router.push(url) }
 function chooseTab(next: string) { if(recordDirty && !window.confirm(t('저장하지 않은 기록을 두고 이동할까요?','Discard the unsaved record and change section?')))return; setTab(next) }
 const scoped = useMemo(()=>company?list.filter(e=>e.company===company):list,[list,company])
 const visible = useMemo(()=>scoped.filter(e=>(status==='all'||e.status===status)&&(department==='all'||e.department===department)&&(!attention||docCount(e)<HR_REQUIREMENTS.length)&&[displayName(e),e.employee_id,e.position,e.department].join(' ').toLowerCase().includes(query.trim().toLowerCase())),[scoped,status,department,attention,query])
 const upcoming = scoped.flatMap(e=>['eval_3month','eval_6month','regularization_date'].flatMap(key=>{const date=String(e[key as keyof HrEmployee]||'');const days=(new Date(date+'T00:00:00+08:00').getTime()-Date.now())/86400000;return date&&days>=-1&&days<=30?[{employee:e,key,date}]:[]})).sort((a,b)=>a.date.localeCompare(b.date))
 const set = (key: keyof HrEmployee,value: unknown) => {setSuccess('');setDraft(old=>old?{...old,[key]:value}:old)}
 async function save(e: React.FormEvent) {
  e.preventDefault();if(!draft)return;setBusy(true);setError('');setSuccess('')
  try{const result=await request('/api/hr/employees',{method:isNew?'POST':'PATCH',body:JSON.stringify(draft)});setEmployee(result.employee);setDraft(result.employee);setEditing(false);setSuccess(t('저장되었습니다.','Changes saved.'));setList(old=>[result.employee,...old.filter(v=>v.id!==result.employee.id)]);if(isNew||result.employee.company!==company)router.replace(`${companyPath(result.employee.company)}/employees/${result.employee.id}`)}catch(err){setError(asError(err))}finally{setBusy(false)}
 }
 if(session===undefined)return <div className="hr-app hr-loading">Loading HR…</div>
 if(!session)return <Login onLogin={s=>{setSession(s);localStorage.setItem('hrSession',JSON.stringify(s));setLang(s.user.username==='may'?'ko':'en')}} />
 const companies=session.user.companies||[]
 const denied = !loading && ((parts.length>0&&!company&&!accountPage&&!lettersPage)||(company&&!companies.includes(company)))
 return <div className="hr-app" lang={lang}>
  <header className="hr-header"><button className="hr-brand" onClick={()=>navigate(ROOT)}><span className="hr-brand-mark">D</span><span>DREAM <b>People</b><small>{t('인사 관리','HR workspace')}</small></span></button><div className="hr-header-right"><span className="hr-scope">{session.user.full?t('전체 회사 관리자','All-company HR'):companies.map(companyLabel).join(' · ')}</span><span className="hr-user">{session.user.username==='may'?'May':session.user.username==='lziem'?'Lziem':session.user.username.charAt(0).toUpperCase()+session.user.username.slice(1)}</span><button className="hr-text-btn" onClick={()=>navigate(ROOT+'/letters')}>{t('공문 작성','Letters')}</button><button className="hr-text-btn" onClick={()=>navigate(ROOT+'/account')}>{t('계정','Account')}</button><button className="hr-text-btn" onClick={()=>{if((dirty||recordDirty)&&!confirm(t('저장하지 않은 내용을 두고 로그아웃할까요?','Discard unsaved changes and sign out?')))return;localStorage.removeItem('hrSession');setSession(null)}}>{t('로그아웃','Sign out')}</button></div></header>
  <main className="hr-main">
   <nav className="hr-breadcrumb" aria-label={t('현재 위치','Breadcrumb')}><button onClick={()=>navigate(ROOT)}>{t('회사별 인사 관리','Companies')}</button>{company&&<><span>/</span><button onClick={()=>navigate(companyPath(company))}>{companyLabel(company)}</button></>}{employeeId&&<><span>/</span><span>{isNew?t('신규 직원','New employee'):employee?displayName(employee):t('직원 상세','Employee profile')}</span></>}</nav>
   {error&&<div className="hr-alert" role="alert">{error}<button onClick={()=>void refresh()}>{t('목록 다시 불러오기','Reload directory')}</button></div>}
   {success&&<div className="hr-success" role="status">{success}</div>}
   {loading?<div className="hr-loading">{t('권한과 직원 정보를 확인하고 있습니다…','Checking access and loading employees…')}</div>:denied?<div className="hr-empty"><h1>{t('접근할 수 없는 회사입니다.','This company is not available to your account.')}</h1><button className="hr-btn primary" onClick={()=>navigate(ROOT)}>{t('내 회사로 이동','Back to my companies')}</button></div>:accountPage||session.user.must_change_pw?<PasswordPage request={request} t={t} force={!!session.user.must_change_pw} onSaved={()=>{setSession(s=>s?{...s,user:{...s.user,must_change_pw:false}}:s);setSuccess(t('비밀번호가 변경되었습니다.','Password changed.'));router.push(ROOT)}}/>:lettersPage?<LetterWorkspace companies={companies} language={lang} onDirty={setRecordDirty}/>:employeeId?<>
    {detailLoading?<div className="hr-loading">{t('직원 기록을 불러오고 있습니다…','Loading employee profile…')}</div>:draft&&employee?<>
     <section className="hr-profile-head"><div className="hr-avatar">{displayName(draft).slice(0,1)}</div><div><p className="hr-eyebrow">{companyLabel(company!)} / {draft.employee_id||t('새 인사 기록','New employee record')}</p><h1>{isNew?t('신규 직원 등록','Add an employee'):displayName(draft)}</h1><p>{[draft.position,draft.department].filter(Boolean).join(' · ')||t('소속과 근무 정보를 작성해주세요.','Complete the company and employment details.')}</p><div className="hr-inline"><span className={'hr-badge '+(draft.status==='Inactive'?'muted':'')}>{valueLabel(draft.status)}</span><span>{valueLabel(draft.employment_status)}</span><span>{t('입사','Joined')} {draft.date_hired||'—'}</span></div></div><div className="hr-profile-actions"><button className="hr-btn" onClick={()=>navigate(companyPath(company!))}>← {t('직원 목록','Employee directory')}</button>{!editing&&<button className="hr-btn primary" onClick={()=>{setEditing(true);if(tab==='overview'||tab==='records')setTab('personal')}}>{t('정보 수정','Edit profile')}</button>}</div></section>
     <div className="hr-detail-layout"><nav className="hr-section-nav" aria-label={t('직원 상세 메뉴','Employee sections')}><button className={tab==='overview'?'selected':''} onClick={()=>chooseTab('overview')}>{t('직원 요약','Overview')}</button>{HR_SECTIONS.map(s=><button key={s.id} className={tab===s.id?'selected':''} onClick={()=>chooseTab(s.id)}>{s[lang]}</button>)}<button className={tab==='records'?'selected':''} onClick={()=>chooseTab('records')}>{t('평가·면담·교육 기록','Activity & records')}<span>{records.length}</span></button><div className="hr-side-note">{t('입사 서류 제출','Requirements received')}<strong>{docCount(draft)} / {HR_REQUIREMENTS.length}</strong><progress value={docCount(draft)} max={HR_REQUIREMENTS.length}/><p>{t('해당 직원에게 필요한 서류인지 확인 후 체크하세요.','Check which requirements apply to this employee before marking received.')}</p></div></nav>
     <div className="hr-detail-content">
      {tab==='overview'?<><section className="hr-card"><div className="hr-card-heading"><div><p className="hr-eyebrow">EMPLOYEE FILE</p><h2>{t('직원 정보 한눈에 보기','Employee at a glance')}</h2></div></div><dl className="hr-summary-grid">{[[t('소속 회사','Company'),companyLabel(draft.company||'')],[t('직책 / 부서','Position / department'),[draft.position,draft.department].filter(Boolean).join(' / ')],[t('보고 대상','Reporting manager'),draft.reporting_to],[t('근무지','Work location'),draft.work_location],[t('연락처','Phone'),draft.contact_number],[t('회사 이메일','Work email'),draft.company_email],[t('근무 시간','Work hours'),[draft.time_in,draft.time_out].filter(Boolean).join(' – ')],[t('비상 연락','Emergency contact'),[draft.emergency_contact_name,draft.emergency_contact_number].filter(Boolean).join(' · ')]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b||t('미입력','Not provided')}</dd></div>)}</dl></section><section className="hr-card"><h2>{t('주요 일정','Milestones')}</h2><div className="hr-milestones">{[['date_hired','입사일','Hire date'],['eval_3month','3개월 평가','3-month evaluation'],['eval_6month','6개월 평가','6-month evaluation'],['regularization_date','정규직 전환','Regularization']].map(([key,ko,en])=><div key={key}><small>{t(ko,en)}</small><strong>{String(draft[key as keyof HrEmployee]||'—')}</strong></div>)}</div></section><section className="hr-card"><div className="hr-card-heading"><h2>{t('최근 인사 기록','Latest HR records')}</h2><button className="hr-btn" onClick={()=>chooseTab('records')}>{t('기록 작성 / 전체 보기','Add / view records')}</button></div>{recordError?<p role="alert">{recordError}</p>:records.length?records.slice(0,3).map(r=><article className="hr-record" key={r.id}><small>{r.occurred_on} · {t(...kindLabels[r.kind])}</small><h3>{r.title}</h3><p>{r.content}</p></article>):<p className="hr-muted">{t('평가, 면담, 교육 내용을 날짜별로 남겨보세요.','Keep dated evaluations, meetings and training notes here.')}</p>}</section></>:tab==='records'?<RecordPanel id={draft.id} records={records} error={recordError} request={request} t={t} onDirty={setRecordDirty} onAdded={r=>setRecords(old=>[r,...old].sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on)))} />:<form id="hr-profile-form" onSubmit={save}>
       <div className="hr-section-title"><h2>{HR_SECTIONS.find(s=>s.id===tab)?.[lang]}</h2><p>{editing?t('필수 항목 *를 확인하고 작성 후 저장해주세요.','Complete the required fields (*) and save your changes.'):t('현재 저장된 직원 정보입니다.','Saved employee information.')}</p></div>
       {HR_SECTIONS.find(s=>s.id===tab)?.groups.map(group=><section className="hr-card" key={group.en}><h3>{group[lang]}</h3><div className="hr-field-grid">{group.fields.map(field=><EmployeeField key={field.key} field={field} value={draft[field.key]} edit={editing} lang={lang} companies={companies} onChange={v=>set(field.key,v)}/>)}</div></section>)}
       {tab==='pay'&&<p className="hr-help">{t('금액은 PHP 기준입니다. 일급은 월급으로 자동 환산하지 않으며, 실제 급여 정산은 근무일과 공제 내역을 별도로 확인해야 합니다.','Amounts are in PHP. Daily pay is not converted to monthly pay; actual payroll requires workdays and deductions.')}</p>}
       {tab==='onboarding'&&<section className="hr-card"><h3>{t('입사 서류 체크리스트','Requirements checklist')} · {docCount(draft)}/{HR_REQUIREMENTS.length}</h3><p className="hr-muted">{t('수령한 서류만 체크하세요. 원본 항목을 그대로 보존하며 해당 여부는 메모에 남길 수 있습니다.','Mark only documents received. Use notes for requirements that do not apply.')}</p><div className="hr-requirements">{HR_REQUIREMENTS.map(r=><label key={r.key} className={draft.requirements?.[r.key]?'received':''}><input type="checkbox" disabled={!editing} checked={!!draft.requirements?.[r.key]} onChange={e=>set('requirements',{...draft.requirements,[r.key]:e.target.checked})}/>{lang==='ko'?REQUIREMENT_KO[r.key]:r.label}</label>)}</div><button type="button" className="hr-text-btn" onClick={()=>chooseTab('records')}>{t('온보딩 교육 기록 작성 →','Add onboarding / orientation record →')}</button></section>}
       {tab==='documents'&&<DocumentPanel documents={draft.documents||[]} editing={editing} t={t} onChange={d=>set('documents',d)}/>}
      </form>}
      {editing&&<div className="hr-savebar"><span>{dirty?t('저장하지 않은 변경 사항','Unsaved changes'):t('편집 중','Editing profile')}</span><button className="hr-btn" disabled={busy} onClick={()=>{if(dirty&&!confirm(t('변경 내용을 취소할까요?','Discard changes?')))return;setDraft(employee);setEditing(false);if(isNew)navigate(companyPath(company!))}}>{t('취소','Cancel')}</button><button className="hr-btn primary" disabled={busy} onClick={()=>{const form=document.getElementById('hr-profile-form') as HTMLFormElement|null;if(!draft.first_name?.trim()||!draft.last_name?.trim()){setTab('personal');setError(t('이름과 성을 입력해주세요.','First and last name are required.'));return}if(form)form.requestSubmit();else void save({preventDefault:()=>{}} as React.FormEvent)}}>{busy?t('저장 중…','Saving…'):t('변경 사항 저장','Save changes')}</button></div>}
     </div></div>
    </>:!error&&<div className="hr-empty">{t('직원을 찾을 수 없습니다.','Employee not found.')}</div>}
   </>:<>
    <section className="hr-page-heading"><div><p className="hr-eyebrow">PEOPLE & ORGANIZATION</p><h1>{company?companyLabel(company):t('우리 회사의 사람들','Your people, in one place')}</h1><p>{company?t('직원별 정보와 입사 준비, 평가 일정을 확인하세요.','Manage employee profiles, onboarding and upcoming milestones.'):t('회사를 선택하면 소속 직원의 상세 인사 기록으로 이동합니다.','Choose a company to manage its people and employee records.')}</p></div>{company&&<button className="hr-btn primary" onClick={()=>navigate(companyPath(company)+'/employees/new')}>+ {t('직원 등록','Add employee')}</button>}</section>
    {!company&&<div className="hr-company-grid">{companies.map((co,index)=>{const employees=list.filter(e=>e.company===co);return <button key={co} className={'hr-company co-'+HR_COMPANY_SLUGS[co]} onClick={()=>navigate(companyPath(co))}><span className="hr-company-top"><span className="hr-company-symbol">{index===0?'DA':COMPANY_EN[co]?.split(' ').map(s=>s[0]).join('')||co}</span><span>↗</span></span><h2>{companyLabel(co)}</h2><p>{t('직원','Employees')} <strong>{employees.length}</strong></p><div className="hr-company-meta"><span>{t('재직','Active')} {employees.filter(e=>e.status==='Active').length}</span><span>{t('서류 확인','Requirements to review')} {employees.filter(e=>docCount(e)<HR_REQUIREMENTS.length).length}</span></div><span className="hr-company-link">{t('직원 목록 열기','Open company')} →</span></button>})}</div>}
    <div className="hr-stats"><div><small>{t('전체 직원','Total employees')}</small><strong>{scoped.length}</strong></div><div><small>{t('재직 중','Active employees')}</small><strong>{scoped.filter(e=>e.status==='Active').length}</strong></div><div><small>{t('수습 중','Probationary')}</small><strong>{scoped.filter(e=>e.status==='Active'&&e.employment_status==='Probationary').length}</strong></div><div><small>{t('30일 내 주요 일정','Milestones in 30 days')}</small><strong>{upcoming.length}</strong></div></div>
    {upcoming.length>0&&<section className="hr-upcoming"><h2>{t('다가오는 평가·전환 일정','Upcoming evaluations & regularization')}</h2><div>{upcoming.slice(0,6).map(item=><button key={item.employee.id+item.key} onClick={()=>navigate(companyPath(item.employee.company!)+ '/employees/'+item.employee.id)}><b>{item.date}</b><span>{displayName(item.employee)}</span><small>{t(item.key==='eval_3month'?'3개월 평가':item.key==='eval_6month'?'6개월 평가':'정규직 전환',item.key==='eval_3month'?'3-month evaluation':item.key==='eval_6month'?'6-month evaluation':'Regularization')}</small></button>)}</div></section>}
    <section className="hr-directory hr-card"><div className="hr-card-heading"><div><h2>{company?t('직원 목록','Employee directory'):t('전체 직원 목록','All employees')}</h2><p className="hr-muted">{t('직원 이름을 누르면 전용 상세 페이지가 열립니다.','Select an employee to open their full profile.')}</p></div><span>{visible.length} {t('명','employees')}</span></div><div className="hr-filters"><label><span>{t('직원 검색','Search employees')}</span><input placeholder={t('이름, 사원번호, 직책, 부서','Name, ID, position or department')} value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span>{t('재직 상태','Status')}</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('전체','All statuses')}</option><option value="Active">{t('재직','Active')}</option><option value="Inactive">{t('퇴사·비활성','Inactive')}</option></select></label><label><span>{t('부서','Department')}</span><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">{t('전체 부서','All departments')}</option>{Array.from(new Set(scoped.map(e=>e.department).filter(Boolean))).map(d=><option key={d} value={d}>{valueLabel(d)}</option>)}</select></label><label className="hr-check-filter"><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/>{t('서류 미완료','Incomplete requirements')}</label></div><div className="hr-table-wrap"><table><thead><tr>{[t('직원','Employee'),t('직책 · 부서','Position · department'),t('소속','Company'),t('입사일','Hire date'),t('고용 형태','Employment'),t('서류','Requirements'),t('상태','Status')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(e=><tr key={e.id}><td><button className="hr-employee-link" onClick={()=>navigate(companyPath(e.company!)+ '/employees/'+e.id)}><span className="hr-avatar small">{displayName(e).slice(0,1)}</span><span><b>{displayName(e)}</b><small>{e.employee_id||'—'}</small></span></button></td><td><b>{e.position||'—'}</b><small>{valueLabel(e.department)}</small></td><td>{companyLabel(e.company||'')}</td><td>{e.date_hired||'—'}</td><td>{valueLabel(e.employment_status)}</td><td><span className="hr-doc-count">{docCount(e)}/{HR_REQUIREMENTS.length}</span></td><td><span className={'hr-badge '+(e.status==='Inactive'?'muted':'')}>{valueLabel(e.status)}</span></td></tr>)}</tbody></table></div>{!visible.length&&<div className="hr-empty"><h3>{scoped.length?t('조건에 맞는 직원이 없습니다.','No employees match these filters.'):t('아직 등록된 직원이 없습니다.','No employees have been added yet.')}</h3><p>{company?t('신규 직원 등록으로 이 회사의 인사 기록을 시작하세요.','Add an employee to start this company’s HR records.'):t('회사를 먼저 선택해주세요.','Choose a company to get started.')}</p>{company&&<button className="hr-btn primary" onClick={()=>navigate(companyPath(company)+'/employees/new')}>{t('첫 직원 등록','Add first employee')}</button>}</div>}</section>
   </>}
  </main>
 </div>
}

function EmployeeField({field,value,edit,lang,companies,onChange}:{field:Field;value:unknown;edit:boolean;lang:Lang;companies:string[];onChange:(value:string)=>void}) {
 const val=value==null?'':String(value),options=field.key==='company'?companies:field.options
 const label=(v:string)=>lang==='ko'?VALUE_KO[v]||v:COMPANY_EN[v]||v
 const id='hr-'+field.key
 return <div className={'hr-field '+(field.full?'wide':'')}><label htmlFor={id}>{field[lang]}{field.required&&<span className="hr-required"> *</span>}</label>{!edit?<div className={'hr-field-value '+(!val?'blank':'')}>{val?label(val):lang==='ko'?'미입력':'Not provided'}</div>:options?<><input id={id} value={val} onChange={e=>onChange(e.target.value)} list={id+'-options'} hidden={['company','status','employment_status','salary_type','gender','civil_status','job_level','cost_center','shift_schedule'].includes(field.key)}/>{['company','status','employment_status','salary_type','gender','civil_status','job_level','cost_center','shift_schedule'].includes(field.key)?<select id={id+'-select'} aria-label={field[lang]} value={val} required={field.required} onChange={e=>onChange(e.target.value)}><option value="">{lang==='ko'?'선택하세요':'Select'}</option>{val&&!options.includes(val)&&<option value={val}>{label(val)}</option>}{options.map(o=><option key={o} value={o}>{label(o)}</option>)}</select>:<datalist id={id+'-options'}>{options.map(o=><option key={o} value={o}>{label(o)}</option>)}</datalist>}</>:field.type==='textarea'?<textarea id={id} rows={6} value={val} onChange={e=>onChange(e.target.value)}/>:<input id={id} value={val} type={field.type||'text'} required={field.required} min={field.type==='number'?0:undefined} step={field.type==='number'?'0.01':undefined} onChange={e=>onChange(e.target.value)}/>} {edit&&field.hint&&<small>{field.hint[lang==='ko'?0:1]}</small>}</div>
}

type T=(ko:string,en:string)=>string
type RequestFn=(url:string,init?:RequestInit)=>Promise<any>
function Login({onLogin}:{onLogin:(s:Session)=>void}) {
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/hr/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw Error(j.error);onLogin({token:j.token,user:j.user})}catch(e){setError(asError(e))}finally{setBusy(false)}}
 return <div className="hr-app hr-login"><div className="hr-login-story"><span className="hr-eyebrow">DREAM PEOPLE</span><h1>People first.<br/>Details together.</h1><p>Employee profiles, onboarding and HR records.<br/>One workspace for your company.</p><span>ACADEMY / DREAM HOUSE / MORI / 88</span></div><form onSubmit={submit} className="hr-login-form"><h2>HR 로그인 / Sign in</h2><p>회사별 인사 관리 · Company HR workspace</p><label>아이디 / Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label>비밀번호 / Password<input autoComplete="current-password" required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="hr-alert">{error}</p>}<button className="hr-btn primary" disabled={busy}>{busy?'확인 중 / Signing in…':'로그인 / Sign in'}</button></form></div>
}
function DocumentPanel({documents,editing,t,onChange}:{documents:NonNullable<HrEmployee['documents']>;editing:boolean;t:T;onChange:(docs:NonNullable<HrEmployee['documents']>)=>void}) {
 return <section className="hr-card"><h3>{t('문서 링크','Document links')}</h3><p className="hr-muted">{t('계약서·증명서 등의 보관 링크와 문서명을 기록하세요. 파일 접근 권한은 원본 저장소에서 관리합니다.','Save links to contracts and certificates. File access remains controlled by the original storage provider.')}</p>{documents.map((d,i)=><div className="hr-document" key={i}>{editing?<><input aria-label={t('문서명','Document name')} placeholder={t('문서명','Document name')} required value={d.name} onChange={e=>onChange(documents.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/><input aria-label={t('문서 주소','Document URL')} type="url" pattern="https://.*" placeholder="https://" required value={d.url} onChange={e=>onChange(documents.map((v,j)=>j===i?{...v,url:e.target.value}:v))}/><button className="hr-text-btn" type="button" onClick={()=>onChange(documents.filter((_,j)=>j!==i))}>{t('제거','Remove')}</button></>:<><b>{d.name}</b>{/^https:\/\//i.test(d.url)&&<a href={d.url} target="_blank" rel="noreferrer">{t('문서 열기 ↗','Open document ↗')}</a>}</>}</div>)}{!documents.length&&<p>{t('등록된 문서 링크가 없습니다.','No document links yet.')}</p>}{editing&&documents.length<50&&<button className="hr-btn" type="button" onClick={()=>onChange([...documents,{name:'',url:''}])}>+ {t('문서 링크 추가','Add document link')}</button>}</section>
}
function RecordPanel({id,records,error,request,t,onAdded,onDirty}:{id:string;records:RecordEntry[];error:string;request:RequestFn;t:T;onAdded:(r:RecordEntry)=>void;onDirty:(v:boolean)=>void}) {
 const [kind,setKind]=useState('note'),[date,setDate]=useState(today()),[follow,setFollow]=useState(''),[title,setTitle]=useState(''),[content,setContent]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState('all')
 useEffect(()=>{onDirty(!!title||!!content||!!follow)},[title,content,follow,onDirty])
 useEffect(()=>()=>onDirty(false),[onDirty])
 if(!id)return <div className="hr-card">{t('직원 정보를 먼저 저장하면 기록을 추가할 수 있습니다.','Save this employee before adding HR records.')}</div>
 return <><section className="hr-card"><h2>{t('평가·면담·교육 기록','Activity & HR records')}</h2><p className="hr-muted">{t('기록일과 작성자가 함께 보관됩니다. 이전 내용을 지우지 않고 후속 기록을 추가해 흐름을 남기세요.','Entries retain their date and author. Add follow-up notes to preserve the employee’s history.')}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const data=await request('/api/hr/records',{method:'POST',body:JSON.stringify({employee_id:id,kind,title,content,occurred_on:date,follow_up_on:follow})});onAdded(data.record);setTitle('');setContent('');setFollow('');onDirty(false);setMessage(t('기록이 저장되었습니다.','Record saved.'))}catch(e){setMessage(asError(e))}finally{setBusy(false)}}}><div className="hr-field-grid"><label>{t('기록 유형','Record type')}<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kindLabels).map(([key,l])=><option value={key} key={key}>{t(...l)}</option>)}</select></label><label>{t('기록일','Record date')}<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>{t('후속 확인일 (선택)','Follow-up date (optional)')}<input type="date" value={follow} onChange={e=>setFollow(e.target.value)}/></label><label className="wide">{t('제목','Title')}<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder={t('예: 3개월 평가 면담 / 입사 오리엔테이션','Example: 3-month review / New hire orientation')}/></label><label className="wide">{t('상세 내용','Details')}<textarea required maxLength={12000} rows={6} value={content} onChange={e=>setContent(e.target.value)} placeholder={t('진행 내용, 합의 사항, 다음 할 일을 기록해주세요.','Record the discussion, agreements and next steps.')}/></label></div>{message&&<p role="status">{message}</p>}<button className="hr-btn primary" disabled={busy}>{busy?t('저장 중…','Saving…'):t('기록 저장','Save record')}</button></form></section><section className="hr-card"><div className="hr-card-heading"><h2>{t('누적 기록','Record history')} · {records.length}</h2><select aria-label={t('기록 필터','Filter records')} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('전체 유형','All types')}</option>{Object.entries(kindLabels).map(([k,l])=><option key={k} value={k}>{t(...l)}</option>)}</select></div>{error&&<p role="alert">{error}</p>}{records.filter(r=>filter==='all'||r.kind===filter).map(r=><article key={r.id} className="hr-record"><div className="hr-inline"><span className="hr-badge">{t(...kindLabels[r.kind])}</span><small>{r.occurred_on} · {r.created_by}</small></div><h3>{r.title}</h3><p>{r.content}</p>{r.follow_up_on&&<footer>{t('후속 확인','Follow up')} · {r.follow_up_on}</footer>}</article>)}{!records.length&&!error&&<p className="hr-muted">{t('아직 기록이 없습니다. 위에서 첫 기록을 남겨주세요.','No records yet. Add the first entry above.')}</p>}</section></>
}
function PasswordPage({request,t,onSaved,force}:{request:RequestFn;t:T;onSaved:()=>void;force:boolean}) {
 const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirmPw,setConfirmPw]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 return <form className="hr-card hr-password" onSubmit={async e=>{e.preventDefault();if(next!==confirmPw){setError(t('새 비밀번호가 일치하지 않습니다.','New passwords do not match.'));return}setBusy(true);setError('');try{await request('/api/hr/password',{method:'POST',body:JSON.stringify({current,next})});onSaved()}catch(e){setError(asError(e))}finally{setBusy(false)}}}><h1>{t('비밀번호 변경','Change password')}</h1>{force&&<p>{t('첫 로그인입니다. 본인만 아는 비밀번호로 변경해주세요.','For your first sign-in, choose your own password.')}</p>}<label>{t('현재 비밀번호','Current password')}<input type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>{t('새 비밀번호 (6자 이상)','New password (at least 6 characters)')}<input type="password" autoComplete="new-password" minLength={6} required value={next} onChange={e=>setNext(e.target.value)}/></label><label>{t('새 비밀번호 확인','Confirm new password')}<input type="password" autoComplete="new-password" required value={confirmPw} onChange={e=>setConfirmPw(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="hr-btn primary" disabled={busy}>{busy?t('저장 중…','Saving…'):t('비밀번호 변경','Change password')}</button></form>
}
