'use client'
import {useState,useEffect,useCallback} from 'react'
import {defaultRules,DEFAULT_POLICY,type PayRule,type PayPolicy} from '@/lib/hrPayRules'
import {COMPANY_EN} from '@/lib/hrFields'
type Props={request:(url:string,init?:RequestInit)=>Promise<any>;language:'ko'|'en';companies?:string[];employeeId?:string;onDirty:(value:boolean)=>void}
export const METHODS:Record<string,[string,string]>={basic:['직원 기본급 기준','Employee base pay'],fixed:['회차별 고정액','Fixed per payday'],monthly:['월 금액 배분','Monthly amount'],days:['근무일 × 단가','Workdays × rate'],hours:['실근무시간 × 단가','Worked hours × rate'],overtime:['연장시간 × 시급','Overtime hours × hourly rate'],percent_basic:['기본급의 비율(%)','Percentage of base pay (%)']}
export default function PaySettings({request,language,companies=[],employeeId,onDirty}:Props){
 const t=(a:string,b:string)=>language==='ko'?a:b
 const [company,setCompany]=useState(companies[0]||''),[rules,setRules]=useState<PayRule[]>(defaultRules()),[policy,setPolicy]=useState<PayPolicy>(DEFAULT_POLICY),[version,setVersion]=useState(0),[values,setValues]=useState<Record<string,number>>({}),[saved,setSaved]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false),[manage,setManage]=useState(false),[loaded,setLoaded]=useState(false),[employee,setEmployee]=useState<any>(null)
 const load=useCallback(async()=>{setLoading(true);setLoaded(false);setManage(false);setError('');try{const r=await request('/api/hr/payroll-settings?'+(employeeId?'employee='+employeeId:'company='+encodeURIComponent(company)));setRules(r.settings.rules);setPolicy(r.settings.policy);setVersion(employeeId?r.employee.payroll_version:r.settings.version);setValues(r.employee?.payroll_values||{});setEmployee(r.employee);setManage(r.can_manage);setLoaded(true);setDirty(false)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[request,employeeId,company])
 useEffect(()=>{void load()},[load]);useEffect(()=>{onDirty(dirty);return()=>onDirty(false)},[dirty,onDirty])
 const update=(id:string,patch:Partial<PayRule>)=>{setDirty(true);setSaved('');setRules(old=>old.map(r=>r.id===id?{...r,...patch}:r))}
 const save=async()=>{setBusy(true);setError('');setSaved('');try{await request('/api/hr/payroll-settings',{method:'POST',body:JSON.stringify(employeeId?{employee_id:employeeId,version,values}:{company,version,rules,policy})});await load();setSaved(t('저장되었습니다. 급여대장에서 프로필 기준으로 계산을 눌러 적용하세요.','Saved. Use Calculate from profile in the payroll register to apply these settings.'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <section className="hr-card">{t('급여 설정 불러오는 중…','Loading payroll settings…')}</section>
 return <section className="hr-card hr-pay-settings"><div className="hr-card-heading"><div><p className="hr-eyebrow">{employeeId?'EMPLOYEE PAY RATES':'PAYROLL SETUP'}</p><h2>{employeeId?t('개인별 급여·공제 금액','Employee pay & deduction rates'):t('급여 항목·계산 기준 설정','Payroll items & calculation rules')}</h2></div>{!employeeId&&<label>{t('회사','Company')}<select disabled={busy} value={company} onChange={e=>{if(dirty&&!confirm(t('저장하지 않은 변경을 취소할까요?','Discard unsaved changes?')))return;setSaved('');setCompany(e.target.value)}}>{companies.map(c=><option key={c} value={c}>{language==='ko'?c:COMPANY_EN[c]||c}</option>)}</select></label>}</div>
 {error&&<p className="hr-alert" role="alert">{error}<button className="hr-btn" type="button" onClick={()=>{if(!dirty||confirm(t('입력 내용을 버리고 다시 불러올까요?','Discard edits and reload?')))void load()}}>{t('다시 불러오기','Reload')}</button></p>}{saved&&<p className="hr-success" role="status">{saved}</p>}
 <p>{employeeId?t('기본급은 위의 기본급·급여 기준에서 저장합니다. 아래 금액은 이 직원에게만 적용됩니다. 빈칸은 회사 공통값, 0은 지급·공제 없음입니다.','Save basic salary and pay basis in the profile fields above. Values below apply only to this employee. Blank uses the company rate; 0 means no amount.'):t('Abby와 Bella가 직접 항목과 계산법을 관리합니다. 회사별로 저장하며 새 계산에 적용됩니다. 기존 급여는 다시 계산하기 전까지 바뀌지 않습니다.','Abby and Bella can manage items and formulas here. Settings apply per company to new calculations. Existing payroll stays unchanged until explicitly recalculated.')}</p>
 {!employeeId&&version===0&&<p className="hr-alert">{t('아직 회사 기준을 저장하지 않았습니다. 아래 시작값을 확인하고 회사의 실제 기준으로 수정한 뒤 저장해주세요.','Company policy has not been saved. Review these starting values, replace them with your company’s actual rules, and save before calculating.')}</p>}{!manage&&<p>{t('항목과 직원별 단가 수정은 Abby·Bella·May가 할 수 있습니다.','Abby, Bella and May can edit items and employee rates.')}</p>}
 {employeeId?<><p className="hr-help">{t('저장된 기본급','Saved basic salary')}: {employee?.basic_salary??'—'} PHP · {employee?.salary_type||'—'}</p><div className="hr-field-grid">{rules.filter(r=>r.id!=='basic'&&r.active).map(r=><label key={r.id}>{language==='ko'?r.name_ko||r.name:r.name} <small>{r.kind==='earning'?t('지급','Earning'):t('공제','Deduction')} · {METHODS[r.method]?.[language==='ko'?0:1]}</small><input type="number" aria-label={r.name} disabled={!manage||busy} min="0" max="10000000" step="0.01" placeholder={`${t('회사 공통','Company')}: ${r.amount}`} value={values[r.id]??''} onChange={e=>{setSaved('');setDirty(true);setValues(old=>{const next={...old};if(e.target.value==='')delete next[r.id];else next[r.id]=Number(e.target.value);return next})}}/><small>{r.schedule==='both'?t('5일·20일 모두','Both paydays'):r.schedule+t('일 지급분',' payday')} · ×{r.multiplier}</small></label>)}</div></>:<>
 <div className="hr-rule-guide"><strong>{t('계산 방식 안내','How calculations work')}</strong><p>{t('기본급: 월급은 1/2, 일급은 휴게 제외 일반근무시간 ÷ 1일 기준시간 × 일급입니다. 일급의 짧은 근무일은 시간 비례로 계산합니다. 월급의 결근·미근무 공제는 별도 항목에서 입력합니다.','Base pay: monthly salary ÷ 2; daily pay = regular hours after breaks ÷ daily hours × daily rate. Short days are prorated for daily-paid employees. Enter absence/undertime deductions separately for monthly-paid employees.')}</p><p>{t('월 금액: 양쪽 지급일이면 1/2씩, 한쪽 지급일이면 전액입니다. 연장근무 단가 0은 기본급에서 시급을 계산하며, 개인 단가를 0으로 지정하면 연장수당도 0입니다. 비율 항목은 해당 회차 기본급을 기준으로 합니다.','Monthly amounts split in half for both paydays, or apply in full on the selected payday. Overtime company rate 0 derives the hourly rate from base salary; an employee override of 0 yields zero overtime pay. Percentage items use this period’s calculated base pay.')}</p></div>
 <div className="hr-field-grid">{[['daily_hours',t('1일 일반근무 기준(시간)','Regular hours per day')],['overtime_min_minutes',t('연장근무 최소 인정(분)','Minimum overtime minutes per day')],['monthly_workdays',t('월급을 시급으로 환산할 근무일수','Workdays divisor for monthly hourly rate')],['submission_end_second',t('하반기 제출 마감: 다음 달 며칠','Second-half submission deadline: day of next month')]].map(([key,label])=><label key={key}>{label}<input disabled={!manage||busy} type="number" step={key==='daily_hours'||key==='monthly_workdays'?'0.5':'1'} value={policy[key as keyof PayPolicy]} onChange={e=>{setSaved('');setDirty(true);setPolicy({...policy,[key]:Number(e.target.value)})}}/></label>)}</div>
 <p className="hr-help">{t('휴게시간은 타임카드에 입력한 실제 분을 차감합니다. 연장 최소시간 미만은 0, 이상이면 초과시간 전체를 계산합니다. 아래 단가 × 수량 × 배율로 계산합니다.','Actual break minutes come from each timecard. Below the overtime threshold, overtime is zero; at or above it, all excess time is counted. Amount = rate × quantity × multiplier.')}</p>
 {(['earning','deduction'] as const).map(kind=><section key={kind}><h3>{kind==='earning'?t('지급 항목','Earnings'):t('공제 항목','Deductions')}</h3>{rules.filter(r=>r.kind===kind).map(r=><div className={'hr-rule-row '+(!r.active?'disabled':'')} key={r.id}><label>{t('영문 항목명','English name')}<input maxLength={100} disabled={!manage||busy} value={r.name} onChange={e=>update(r.id,{name:e.target.value})}/></label><label>{t('한글 표시명','Korean label')}<input maxLength={100} disabled={!manage||busy} value={r.name_ko} onChange={e=>update(r.id,{name_ko:e.target.value})}/></label><label>{t('계산 방식','Calculation')}<select disabled={!manage||busy||r.id==='basic'} value={r.method} onChange={e=>update(r.id,{method:e.target.value as PayRule['method']})}>{Object.entries(METHODS).filter(([k])=>r.id==='basic'?k==='basic':k!=='basic').map(([k,n])=><option key={k} value={k}>{n[language==='ko'?0:1]}</option>)}</select></label><label>{t('공통 금액 / 단가 / %','Default amount / rate / %')}<input disabled={!manage||busy||r.id==='basic'} type="number" step="0.01" min="0" value={r.amount} onChange={e=>update(r.id,{amount:Number(e.target.value)})}/></label><label>{t('배율','Multiplier')}<input disabled={!manage||busy} type="number" step="0.01" min="0" max="10" value={r.multiplier} onChange={e=>update(r.id,{multiplier:Number(e.target.value)})}/></label><label>{t('적용 지급일','Payday')}<select disabled={!manage||busy} value={r.schedule} onChange={e=>update(r.id,{schedule:e.target.value as PayRule['schedule']})}><option value="both">{t('5일·20일 모두','Both 5th & 20th')}</option><option value="5">{t('5일만','5th only')}</option><option value="20">{t('20일만','20th only')}</option></select></label><label className="hr-rule-active"><input type="checkbox" disabled={!manage||busy||r.id==='basic'} checked={r.active} onChange={e=>update(r.id,{active:e.target.checked})}/>{t('사용','Enabled')}</label></div>)}{manage&&rules.length<60&&<button type="button" className="hr-btn" onClick={()=>{setDirty(true);setSaved('');setRules([...rules,{id:'custom_'+crypto.randomUUID().replaceAll('-',''),name:'',name_ko:'',kind,method:'fixed',amount:0,multiplier:1,schedule:'both',active:true}])}}>+ {kind==='earning'?t('지급 항목 추가','Add earning'):t('공제 항목 추가','Add deduction')}</button>}</section>)}
 </>}
 {manage&&<div className="hr-savebar"><span>{dirty?t('저장하지 않은 변경 사항','Unsaved changes'):t('저장된 기준은 급여 계산 시 불러옵니다.','Saved settings are loaded when calculating payroll.')}</span><button type="button" className="hr-btn primary" disabled={busy||!loaded} onClick={()=>void save()}>{busy?t('저장 중…','Saving…'):t('설정 저장','Save settings')}</button></div>}
 </section>
}

