'use client'
import {useEffect,useState,useRef} from 'react'
type Account={username:string;is_active:boolean;issued_at?:string;issued_by?:string}
export default function StaffAccount({id,firstName,language,request}:{id:string;firstName?:string;language:'ko'|'en';request:(url:string,init?:RequestInit)=>Promise<any>}){
 const handoffRef=useRef<HTMLDivElement>(null)
 const [issuedNow,setIssuedNow]=useState(false)
 const t=(ko:string,en:string)=>language==='ko'?ko:en
 const [username,setUsername]=useState((firstName||'').trim().split(/\s+/)[0].toLowerCase().replace(/[^a-z0-9._-]/g,'')),[account,setAccount]=useState<Account|null>(null),[password,setPassword]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false)
 useEffect(()=>{let alive=true;setLoading(true);setError('');setPassword('');setCopied(false);setIssuedNow(false);setAccount(null);if(!id){setLoading(false);return}request('/api/hr/staff-account?employee='+encodeURIComponent(id)).then(r=>{if(alive){setAccount(r.account);setAvailable(r.available||[])}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id,request])
 const [available,setAvailable]=useState<{id:string;username:string;name:string}[]>([]),[existing,setExisting]=useState('')
 useEffect(()=>{if(issuedNow&&account)handoffRef.current?.scrollIntoView({behavior:'smooth',block:'center'})},[issuedNow,account])
 const handoff=account?`Dream Academy — Staff account\nSign in: https://www.dreamacademyph.com/login\nUsername: ${account.username}\n${password?'Temporary password: '+password:'Password: Please use your existing password.'}\n${password?'Please change your password after your first sign-in.':'If you cannot sign in, please contact HR.'}\nThis account opens the local staff hub; it does not grant HR administrator access.`:''
 return <section className="hr-card"><p className="hr-eyebrow">1. REGISTER EMPLOYEE → 2. ISSUE LOGIN → 3. SHARE PRIVATELY</p><h2>{t('현지직원 아이디 발급','Issue local staff login')}</h2><p>{t('직원 정보를 저장한 뒤 아이디를 발급하고 전달 내용을 복사하세요. HR 관리자 권한은 부여되지 않습니다.','Save the employee profile, issue a login, then copy the details to share privately. This does not grant HR administrator access.')}</p>
 {!id?<p>{t('직원 정보를 먼저 저장해주세요.','Save the employee first.')}</p>:loading?<p>{t('발급 여부 확인 중…','Checking account…')}</p>:account?<><p><b>{t('발급된 아이디','Issued username')}: {account.username}</b> · {account.is_active?t('활성','Active'):t('비활성','Inactive')}</p><p>{account.issued_by} · {account.issued_at?.slice(0,10)}</p>{!password&&<p>{t('이미 발급된 계정입니다. 비밀번호는 저장 후 다시 표시하지 않습니다.','This employee already has an account. Passwords are not displayed again after leaving this page.')}</p>}</>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await request('/api/hr/staff-account',{method:'POST',body:JSON.stringify({employee_id:id,username})});setAccount(r.account);setPassword(r.password||'');setCopied(false);setIssuedNow(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label style={{display:'block',margin:'18px 0'}}>{t('로그인 아이디 (영문 이름)','Login ID (English name)')}<input required minLength={3} maxLength={30} pattern="[a-zA-Z][a-zA-Z0-9._-]{2,29}" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" style={{display:'block',padding:12,marginTop:8}}/></label><p>{t('초기 비밀번호 규칙','Initial password rule')}: <strong>{username.trim().toUpperCase()||'NAME'}2026!</strong></p><p>{t('아이디는 소문자로 저장하고, 비밀번호의 이름 부분은 대문자로 생성합니다. 중복 아이디는 다른 이름으로 바꿔주세요.','The ID is saved in lowercase; the name in the password is uppercase. Choose another ID if it is already taken.')}</p><button className="hr-btn primary" disabled={busy}>{busy?t('발급 중…','Issuing…'):t('아이디 발급','Issue login')}</button>{error&&<button type="button" className="hr-btn" onClick={()=>setError('')}>{t('입력 수정 후 다시 시도','Retry after correcting the ID')}</button>}</form>}
 {!loading&&!account&&available.length>0&&<div style={{marginTop:24,padding:20,border:'1px solid #cbd5e1',borderRadius:12}}><h3>{t('기존 직원 아이디 연결','Link an existing staff login')}</h3><p>{t('이미 로그인 아이디가 있는 직원은 새로 발급하지 말고 본인의 계정을 선택하세요. 이름과 아이디를 확인하세요.','If this employee already has a login, select their existing account. Check both the name and username carefully.')}</p><select aria-label="Existing staff login" value={existing} onChange={e=>setExisting(e.target.value)} disabled={busy}><option value="">{t('직원 계정 선택','Select staff account')}</option>{available.map(a=><option key={a.id} value={a.id}>{a.name} — {a.username}</option>)}</select><button className="hr-btn" disabled={busy||!existing} onClick={async()=>{const a=available.find(v=>v.id===existing);if(!a||!confirm(t('이 직원의 HR 자료를 다음 계정에 연결할까요? ','Link this employee’s private HR record to: ')+a.name+' ('+a.username+')'))return;setBusy(true);setError('');try{const r=await request('/api/hr/staff-account',{method:'POST',body:JSON.stringify({action:'link',employee_id:id,account_id:existing,username:'link-account'})});setAccount(r.account);setCopied(false);setIssuedNow(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{t('선택한 계정 연결','Link selected account')}</button></div>}
 {error&&<p role="alert">{error}</p>}{handoff&&<div ref={handoffRef} style={{marginTop:20,padding:20,background:'#f3f0ff',borderRadius:12}}>{issuedNow&&<p role="status" style={{fontWeight:700,color:'#276749'}}>{t('아이디가 준비되었습니다. 아래 안내를 복사해 직원에게 보내주세요.','Login is ready. Copy the message below and send it to the employee.')}</p>}<h3>{t('직원에게 안내','Message for the employee')}</h3><p>{t('아래 영문 안내를 복사해서 해당 직원에게 전달하세요.','Copy the English message below and share it privately with this employee.')}</p>{!password&&<p>{t('기존 계정은 현재 비밀번호를 사용하도록 안내합니다. 임시 비밀번호는 새로 발급한 직후에만 포함됩니다.','For an existing account, the message asks the employee to use their current password. A temporary password is included only immediately after issuance.')}</p>}<textarea aria-label={t('직원에게 보낼 안내문','Employee login message')} readOnly value={handoff} rows={9} onFocus={e=>e.currentTarget.select()} style={{width:'100%',padding:16,fontSize:16,lineHeight:1.7}}/><button className="hr-btn primary" onClick={async()=>{try{await navigator.clipboard.writeText(handoff);setCopied(true)}catch{setError(t('내용을 선택해 직접 복사해주세요.','Select and copy the text above.'))}}}>{copied?t('복사되었습니다','Copied'):t('직원 안내문 복사','Copy employee message')}</button><p>{t('직원에게 개별 전달한 뒤 이 화면을 닫으세요.','Share privately with this employee, then close this page.')}</p></div>}
 </section>
}




