'use client'
import {useEffect,useState} from 'react'
type Account={username:string;is_active:boolean;issued_at?:string;issued_by?:string}
export default function StaffAccount({id,firstName,language,request}:{id:string;firstName?:string;language:'ko'|'en';request:(url:string,init?:RequestInit)=>Promise<any>}){
 const t=(ko:string,en:string)=>language==='ko'?ko:en
 const [username,setUsername]=useState((firstName||'').trim().split(/\s+/)[0].toLowerCase().replace(/[^a-z0-9._-]/g,'')),[account,setAccount]=useState<Account|null>(null),[password,setPassword]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false)
 useEffect(()=>{let alive=true;setLoading(true);setError('');setPassword('');setAccount(null);if(!id){setLoading(false);return}request('/api/hr/staff-account?employee='+encodeURIComponent(id)).then(r=>{if(alive)setAccount(r.account)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id,request])
 const handoff=account&&password?`Dream Academy — Staff account\nSign in: https://www.dreamacademyph.com/login\nUsername: ${account.username}\nTemporary password: ${password}\nPlease change your password after your first sign-in.\nThis account opens the local staff hub; it does not grant HR administrator access.`:''
 return <section className="hr-card"><p className="hr-eyebrow">1. REGISTER EMPLOYEE → 2. ISSUE LOGIN → 3. SHARE PRIVATELY</p><h2>{t('현지직원 아이디 발급','Issue local staff login')}</h2><p>{t('직원 정보를 저장한 뒤 아이디를 발급하고 전달 내용을 복사하세요. HR 관리자 권한은 부여되지 않습니다.','Save the employee profile, issue a login, then copy the details to share privately. This does not grant HR administrator access.')}</p>
 {!id?<p>{t('직원 정보를 먼저 저장해주세요.','Save the employee first.')}</p>:loading?<p>{t('발급 여부 확인 중…','Checking account…')}</p>:account?<><p><b>{t('발급된 아이디','Issued username')}: {account.username}</b> · {account.is_active?t('활성','Active'):t('비활성','Inactive')}</p><p>{account.issued_by} · {account.issued_at?.slice(0,10)}</p>{!password&&<p>{t('이미 발급된 계정입니다. 비밀번호는 저장 후 다시 표시하지 않습니다.','This employee already has an account. Passwords are not displayed again after leaving this page.')}</p>}</>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await request('/api/hr/staff-account',{method:'POST',body:JSON.stringify({employee_id:id,username})});setAccount(r.account);setPassword(r.password)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label style={{display:'block',margin:'18px 0'}}>{t('로그인 아이디 (영문 이름)','Login ID (English name)')}<input required minLength={3} maxLength={30} pattern="[a-zA-Z][a-zA-Z0-9._-]{2,29}" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" style={{display:'block',padding:12,marginTop:8}}/></label><p>{t('초기 비밀번호 규칙','Initial password rule')}: <strong>{username.trim().toUpperCase()||'NAME'}2026!</strong></p><p>{t('아이디는 소문자로 저장하고, 비밀번호의 이름 부분은 대문자로 생성합니다. 중복 아이디는 다른 이름으로 바꿔주세요.','The ID is saved in lowercase; the name in the password is uppercase. Choose another ID if it is already taken.')}</p><button className="hr-btn primary" disabled={busy}>{busy?t('발급 중…','Issuing…'):t('아이디 발급','Issue login')}</button>{error&&<button type="button" className="hr-btn" onClick={()=>setError('')}>{t('입력 수정 후 다시 시도','Retry after correcting the ID')}</button>}</form>}
 {error&&<p role="alert">{error}</p>}{handoff&&<div style={{marginTop:20,padding:20,background:'#f3f0ff',borderRadius:12}}><h3>{t('직원에게 전달할 내용','Details to share with the employee')}</h3><textarea readOnly value={handoff} rows={8} style={{width:'100%',padding:12}}/><button className="hr-btn primary" onClick={async()=>{try{await navigator.clipboard.writeText(handoff);setCopied(true)}catch{setError(t('내용을 선택해 직접 복사해주세요.','Select and copy the text above.'))}}}>{copied?t('복사되었습니다','Copied'):t('전달 내용 복사','Copy login details')}</button><p>{t('직원에게 개별 전달한 뒤 이 화면을 닫으세요.','Share privately with this employee, then close this page.')}</p></div>}
 </section>
}


