'use client';
import {useEffect,useState} from 'react';
type Receipt={booking_id:string;student_name:string;paper_at:string|null;medicine_at:string|null;followup_due:string;revision:number;updated_by:string;updated_at:string};
type Booking={id:string;booker_name:string;house_no:string;accom_room:string;checkin_date:string;checkout_date:string;assignee:string;status:string};
export default function MedicationReceipts(){
 const [rows,setRows]=useState<Receipt[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[legacy,setLegacy]=useState<Record<string,unknown>>({});
 const [filter,setFilter]=useState('pending'),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila'}).format(new Date());
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin/medication-receipts'),d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.receipts);setBookings(d.bookings);setLegacy(d.legacy);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();const id=new URLSearchParams(window.location.search).get('bookingId');if(id){setQuery(id);setFilter('all');}},[]);
 async function update(row:Receipt,field:string,value:boolean|string){setBusy(row.booking_id+'|'+row.student_name);setError('');try{const r=await fetch('/api/admin/medication-receipts',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...row,field,value})}),d=await r.json();if(!r.ok)throw Error(d.error);setRows(prev=>prev.map(x=>x.booking_id===row.booking_id&&x.student_name===row.student_name?d.receipt:x));}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const visible=rows.map(r=>({...r,booking:bookings.find(b=>b.id===r.booking_id)})).filter(r=>{const b=r.booking;if(!b||/취소|cancel/i.test(b.status||''))return false;const current=b.checkin_date?.slice(0,10)<=today&&b.checkout_date?.slice(0,10)>=today;return (filter==='all'||filter==='pending'&&current&&!r.medicine_at||filter==='received'&&!!r.medicine_at||filter==='upcoming'&&b.checkin_date?.slice(0,10)>today)&&[r.student_name,b.id,b.booker_name,b.house_no].join(' ').toLowerCase().includes(query.trim().toLowerCase());}).sort((a,b)=>a.followup_due.localeCompare(b.followup_due));
 return <section style={{background:'white',padding:20,borderRadius:12,border:'1px solid #dbe3ee'}}><h2>안내문 전달 · 실제 약 수령</h2><p style={{margin:'12px 0',color:'#64748b'}}>출력한 뒤 실제 전달했을 때, 약을 실제 받았을 때 각각 확인해주세요. 기존 제출 기록은 그대로 보존합니다.</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{[['pending','체류 중 · 약 미수령'],['upcoming','입실 예정'],['received','약 수령 확인'],['all','전체 기록']].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} style={{padding:10,background:filter===v?'#385caa':'#f1f5f9',color:filter===v?'white':'#334155',border:0,borderRadius:6}}>{l}</button>)}<input aria-label="학생·예약자 검색" placeholder="학생 · 예약자 · 룸 검색" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>void load()}>새로고침</button></div>{error&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}{loading?<p>불러오는 중…</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:700,textAlign:'left',borderCollapse:'collapse'}}><thead><tr>{['학생 / 예약자','안내문 전달','실제 약 수령','재안내 확인일','담당 / 최근 변경'].map(l=><th key={l} style={{padding:12,background:'#edf2f8'}}>{l}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.booking_id+r.student_name}><td style={{padding:12,borderBottom:'1px solid #e2e8f0'}}><b>{r.student_name}</b><div>{r.booking!.booker_name} · {r.booking!.house_no||r.booking!.accom_room}</div>{!!legacy[r.booking_id+'|'+r.student_name]&&<small>기존 제출 기록 있음 · 약 수령은 별도 확인</small>}</td><td><label><input disabled={!!busy} type="checkbox" checked={!!r.paper_at} onChange={e=>void update(r,'paper_at',e.target.checked)}/> 전달 확인</label></td><td><label><input disabled={!!busy} type="checkbox" checked={!!r.medicine_at} onChange={e=>void update(r,'medicine_at',e.target.checked)}/> 실제 받음</label></td><td><input aria-label={r.student_name+' 재안내일'} type="date" value={r.followup_due} disabled={!!busy} onChange={e=>{if(e.target.value)void update(r,'followup_due',e.target.value);}}/>{!r.medicine_at&&r.followup_due<=today&&<div style={{color:'#b42318',fontSize:12}}>수령 확인·재안내 필요</div>}</td><td>{r.booking!.assignee||'담당 미배정'}<small style={{display:'block'}}>{r.updated_by==='system'?'':r.updated_by}</small></td></tr>)}</tbody></table>{!visible.length&&<p style={{padding:24}}>해당하는 학생이 없습니다.</p>}</div>}</section>;
}
