'use client';
import {BOOKING3_DAYS,BOOKING3_TIMES,koreaToday} from '@/lib/booking3';
import {addDate,packageBounds,buildPackageSchedule,validatePackagePlan,type PackagePlan,type PackageBooking,type PackageSession} from '@/lib/onlinePackagePlan';
import s from './OnlinePackagePlanEditor.module.css';
export type PackageMeta={admin:boolean;bookings:PackageBooking[];sessions:PackageSession[];holidays:string[];snapshot:string;bookingSnapshot:string;enrollment:any;children:{name:string;english:string}[];existing:any[];plan:PackagePlan};
export default function OnlinePackagePlanEditor({meta,value,onChange,disabled=false}:{meta:PackageMeta;value:PackagePlan;onChange:(p:PackagePlan)=>void;disabled?:boolean}){
  const selected=meta.bookings.filter(b=>value.bookingIds.includes(b.id));const bounds=packageBounds(selected),automatic=bounds.weeks*3;
  const update=(p:Partial<PackagePlan>)=>onChange({...value,...p});
  function total(n:number,manual=value.manual){const pre=Math.min(value.pre.count,n);update({total:n,manual,pre:{...value.pre,count:pre},post:{...value.post,count:Math.max(0,n-pre)}});}
  function distribute(pre:number){const activate=(key:'pre'|'post',count:number)=>{const p=value[key];const days=p.days.length?p.days:['월','수','금'];return {...p,count,days,times:Object.fromEntries(days.map(d=>[d,p.times[d]||'19:00'])),start:p.start||(key==='pre'?addDate(koreaToday(),4):[addDate(koreaToday(),4),bounds.to?addDate(bounds.to,1):''].sort().at(-1)!)};};update({pre:activate('pre',pre),post:activate('post',Math.max(0,value.total-pre))});}
  let preview:ReturnType<typeof buildPackageSchedule>|null=null,error='';
  try{const p=validatePackagePlan(value,meta.bookings,meta.admin);preview=buildPackageSchedule(p,meta.bookings,meta.sessions,new Set(meta.holidays),meta.enrollment?.used_sessions||0);}catch(e){error=(e as Error).message;}
  return <fieldset className={s.root} disabled={disabled}><legend>연수 패키지 · 총 회차와 전후 일정</legend>
    <section className={s.card}><div className={s.title}><h2>1. 연수 기간으로 총 제공 회차 확인</h2><span>연수 1주 = 화상영어 3회</span></div>
      {!meta.bookings.length&&<p role="alert">학생의 연수 예약을 확인하지 못했습니다. 담당자에게 예약 연결을 요청해주세요.</p>}
      <div className={s.bookings}>{meta.bookings.map(b=><label key={b.id} className={s.booking}><input type="checkbox" checked={value.bookingIds.includes(b.id)} disabled={!!b.claimed} onChange={e=>{const ids=e.target.checked?[...value.bookingIds,b.id]:value.bookingIds.filter(id=>id!==b.id);const auto=meta.bookings.filter(x=>ids.includes(x.id)).reduce((n,x)=>n+x.weeks*3,0);const n=value.manual?value.total:auto;onChange({...value,bookingIds:ids,total:n,pre:{...value.pre,count:Math.min(value.pre.count,n)},post:{...value.post,count:Math.max(0,n-Math.min(value.pre.count,n))}});}}/><span><b>{b.number} · {b.weeks}주 → {b.weeks*3}회</b><small>{b.from} ~ {b.to} · {b.basis}{b.claimed?' · 이미 연결된 수강권':''}</small></span></label>)}</div>
      <div className={s.entitlement}><div><small>선택한 연수 {selected.length}건 · 총 {bounds.weeks}주</small><strong>{automatic}<span>회 기본 제공</span></strong><p>수강 요일을 주 2회로 선택해도 제공 회차는 줄어들지 않습니다.</p></div><label>총 제공 회차<input aria-label="총 제공 회차" type="number" min={1} max={1000} readOnly={!meta.admin||!value.manual} value={value.total} onChange={e=>total(Number(e.target.value))}/></label></div>
      {meta.admin&&<><div className={s.actions}><label><input type="checkbox" checked={value.manual} onChange={e=>e.target.checked?update({manual:true}):total(automatic,false)}/> 총 회차 수동 조정</label><button type="button" onClick={()=>total(automatic,false)}>연수 기준 {automatic}회 적용</button></div>{value.manual&&<label className={s.field}>수동 조정 사유<input value={value.reason} maxLength={500} onChange={e=>update({reason:e.target.value})} placeholder="예: 추가 제공 3회 / 기존 이력 포함"/></label>}</>}
    </section>
    <section className={s.card}><h2>2. 연수 전·후에 사용할 회차 배분</h2><p>기본은 전·후 나누어 사용합니다. 전부 연수 전 또는 연수 후에 사용하는 것도 가능합니다.</p><div className={s.actions}><button type="button" onClick={()=>distribute(Math.floor(value.total/6)*3)}>전·후 나누기</button><button type="button" onClick={()=>distribute(value.total)}>전부 연수 전</button><button type="button" onClick={()=>distribute(0)}>전부 연수 후</button></div><div className={s.balance}><b>연수 전 {value.pre.count}회 + 연수 후 {value.post.count}회</b><span>= 총 {value.total}회</span></div>
    <div className={s.parts}>{(['pre','post'] as const).map(key=>{const part=value[key];const set=(p:Partial<typeof part>)=>update({[key]:{...part,...p}});return <section key={key} className={s.part}><h3>{key==='pre'?'연수 전 일정':'연수 후 일정'}</h3><div className={s.row}><label className={s.field}>사용 회차<input aria-label={key==='pre'?'연수 전 회차':'연수 후 회차'} type="number" min={0} max={value.total} value={part.count} onChange={e=>{const n=Math.max(0,Math.min(value.total,Number(e.target.value)));distribute(key==='pre'?n:value.total-n);}}/></label><div className={s.weeks}>주 3회 기준 <b>{Number((part.count/3).toFixed(1))}주</b><small>선택한 주 {part.days.length||3}회 일정은 약 {Math.ceil(part.count/(part.days.length||3))}주</small></div></div>
      {part.count>0?<><label className={s.field}>희망 시작일<input aria-label={key==='pre'?'연수 전 시작일':'연수 후 시작일'} type="date" value={part.start} min={meta.admin?undefined:koreaToday()} onChange={e=>set({start:e.target.value})}/></label><p className={s.bound}>{key==='pre'?`${bounds.from||'연수 시작일'} 전까지 진행`:`${bounds.to||'연수 종료일'} 다음 날부터 진행`}</p><div className={s.days}>{BOOKING3_DAYS.map(d=><button key={d} aria-label={`${key==='pre'?'연수 전':'연수 후'} ${d}요일`} aria-pressed={part.days.includes(d)} className={part.days.includes(d)?s.on:''} type="button" onClick={()=>set({days:part.days.includes(d)?part.days.filter(x=>x!==d):BOOKING3_DAYS.filter(x=>x===d||part.days.includes(x)),times:{...part.times,[d]:part.times[d]||'19:00'}})}>{d}</button>)}</div><div className={s.times}>{part.days.map(d=><label className={s.field} key={d}>{d}요일 · 한국 시간<select value={part.times[d]||'19:00'} onChange={e=>set({times:{...part.times,[d]:e.target.value}})}>{BOOKING3_TIMES.map(t=><option key={t}>{t}</option>)}</select></label>)}</div>{preview&&<p className={s.preview}>첫 수업 {preview.summary[key].first||'—'}<br/>마지막 수업 {preview.summary[key].last||'—'}</p>}</>:<p className={s.bound}>이 기간에는 수업을 배정하지 않습니다.</p>}
    </section>;})}</div><p className={s.note}>휴일·성수기·연수 체류 기간은 자동으로 제외합니다. 두 연수를 선택하면 가장 이른 시작 전 / 가장 늦은 종료 후를 기준으로 나눕니다. 기존 출석·취소·보강 및 기록이 있는 수업은 보존합니다.</p>
    {error?<p className={s.error} role="alert">{error}</p>:<p className={s.preview}>총 {value.total}회 배분 확인 · 저장 시 예정 수업 {preview?.rows.length}개 반영</p>}</section>
  </fieldset>;
}
