import { HR_ACTIVE_STATUS, HR_CIVIL_STATUS, HR_COMPANIES, HR_DEPARTMENTS, HR_DIVISIONS, HR_EMP_STATUS, HR_GENDER, HR_JOB_LEVEL, HR_SALARY_TYPE, HR_TAX_STATUS, type HrEmployee } from './hr'
export type Lang = 'ko' | 'en'
export type Field = { key: keyof HrEmployee; ko: string; en: string; type?: string; options?: string[]; full?: boolean; required?: boolean; hint?: [string,string] }
export type Section = { id: string; ko: string; en: string; groups: { ko: string; en: string; fields: Field[] }[] }
const f = (key: keyof HrEmployee, ko: string, en: string, extra: Partial<Field> = {}): Field => ({ key, ko, en, ...extra })
const date = (key: keyof HrEmployee, ko: string, en: string) => f(key,ko,en,{type:'date'})
const money = (key: keyof HrEmployee, ko: string, en: string) => f(key,ko,en,{type:'number'})
export const COMPANY_EN: Record<string,string> = { '아카데미':'Dream Academy', '드림하우스':'Dream House', '모리':'Mori', '88':'88' }
export const HR_SECTIONS: Section[] = [
 {id:'personal',ko:'인적사항',en:'Personal',groups:[
  {ko:'이름과 기본 정보',en:'Identity',fields:[f('first_name','이름','First name',{required:true}),f('last_name','성','Last name',{required:true}),f('middle_name','중간 이름','Middle name'),f('suffix','접미사','Suffix'),f('gender','성별','Gender',{options:HR_GENDER}),f('civil_status','혼인 상태','Civil status',{options:HR_CIVIL_STATUS}),date('date_of_birth','생년월일','Date of birth'),f('place_of_birth','출생지','Place of birth'),f('nationality','국적','Nationality'),f('religion','종교','Religion')]},
  {ko:'연락처와 주소',en:'Contact & address',fields:[f('contact_number','연락처','Phone number'),f('personal_email','개인 이메일','Personal email',{type:'email'}),f('company_email','회사 이메일','Work email',{type:'email'}),f('current_address','현재 주소','Current address',{full:true}),f('permanent_address','본적 주소','Permanent address',{full:true})]},
  {ko:'비상 연락처',en:'Emergency contact',fields:[f('emergency_contact_name','연락할 사람','Contact name'),f('emergency_relationship','관계','Relationship'),f('emergency_contact_number','비상 연락 번호','Emergency phone'),f('emergency_contact_address','비상 연락 주소','Emergency address',{full:true})]}
 ]},
 {id:'employment',ko:'소속·근무',en:'Employment',groups:[
  {ko:'소속과 역할',en:'Company & role',fields:[f('company','회사','Company',{options:HR_COMPANIES,required:true}),f('employee_id','사원번호','Employee ID',{hint:['비워두면 자동 생성됩니다.','Generated automatically if left blank.']}),f('biometrics_id','출퇴근 기기 번호','Biometrics ID'),f('cost_center','인건비 부문','Cost center',{options:HR_COMPANIES}),f('position','직책','Position'),f('division','본부','Division',{options:HR_DIVISIONS}),f('department','부서','Department',{options:HR_DEPARTMENTS}),f('job_level','직급','Job level',{options:HR_JOB_LEVEL}),f('reporting_to','보고 대상','Reporting manager'),f('status','재직 상태','Active status',{options:HR_ACTIVE_STATUS}),f('employment_status','고용 형태','Employment status',{options:HR_EMP_STATUS})]},
  {ko:'입사·평가 일정',en:'Employment milestones',fields:[date('date_hired','입사일','Hire date'),date('eval_3month','3개월 평가일','3-month evaluation'),date('eval_6month','6개월 평가일','6-month evaluation'),date('regularization_date','정규직 전환일','Regularization date'),date('separation_date','퇴사일','Separation date')]},
  {ko:'근무 일정',en:'Work schedule',fields:[f('work_location','근무지','Work location'),f('shift_schedule','근무조','Shift',{options:['Day','Mid']}),f('time_in','출근 시각','Scheduled time in',{hint:['예: 8:30 AM','Example: 8:30 AM']}),f('time_out','퇴근 시각','Scheduled time out',{hint:['예: 5:00 PM','Example: 5:00 PM']})]}
 ]},
 {id:'pay',ko:'급여·은행',en:'Pay & banking',groups:[
  {ko:'기본급과 수당 · PHP',en:'Base pay & allowances · PHP',fields:[f('salary_type','급여 기준','Pay basis',{options:HR_SALARY_TYPE}),money('basic_salary','기본급 (선택한 급여 기준)','Base salary (selected pay basis)'),f('tax_status','세금 분류','Tax status',{options:HR_TAX_STATUS}),money('allow_position','직책 수당','Position allowance'),money('allow_transpo','픽업·드랍 교통 수당','Pickup / drop-off allowance'),money('allow_tutorial','튜터 수당','Tutorial allowance'),money('allow_load','통신 수당','Load allowance')]},
  {ko:'지급 계좌',en:'Bank details',fields:[f('bank_name','은행','Bank name'),f('bank_account','계좌번호','Account number'),f('bank_status','계좌 상태','Bank account status')]}
 ]},
 {id:'benefits',ko:'정부 등록번호',en:'Government IDs',groups:[{ko:'사회보장·건강보험·주택기금·세금',en:'Benefits & tax registration',fields:[f('sss_no','SSS 번호','SSS number'),f('philhealth_no','PhilHealth 번호','PhilHealth number'),f('pagibig_no','Pag-IBIG 번호','Pag-IBIG number'),f('tin','납세자 번호 (TIN)','Tax identification number (TIN)')]}]},
 {id:'onboarding',ko:'채용·입사 준비',en:'Onboarding',groups:[{ko:'지원 및 입사 진행',en:'Application & onboarding',fields:[f('application_no','지원 번호','Application number'),f('position_applied','지원 직책','Position applied for'),date('date_of_application','지원일','Application date'),f('application_status','지원 진행 상태','Application status'),date('date_submitted','서류 제출일','Submission date'),f('requirement_status','서류 진행 상태','Requirement status'),date('onboarding_date','입사 교육일','Onboarding date')]}]},
 {id:'documents',ko:'서류·메모',en:'Documents & notes',groups:[{ko:'프로필 사진과 참고 메모',en:'Profile photo & general notes',fields:[f('photo_url','프로필 사진 주소','Profile photo URL',{type:'url',full:true,hint:['HTTPS 이미지 주소를 입력하세요.','Use an HTTPS image URL.']}),f('notes','인사 참고 메모','General HR notes',{type:'textarea',full:true})]}]}
]
export const VALUE_KO: Record<string,string> = {Active:'재직',Inactive:'퇴사·비활성',Probationary:'수습',Regular:'정규직',Contractual:'계약직','On Call':'호출 근무',Monthly:'월급',Daily:'일급',Male:'남성',Female:'여성',Single:'미혼',Married:'기혼',Widowed:'사별',Separated:'별거','Solo Parent':'한부모',Executive:'임원','Senior Management':'상위 관리자',Management:'관리자',Supervisory:'현장 감독','Rank & File':'일반 직원',Day:'주간',Mid:'중간조','Executive Division':'경영 본부','Human Resources':'인사','Finance & Accounting':'재무·회계','Operations Division':'운영 본부','Executive Office':'경영 사무실','Corporate/Facility':'총무·시설','Admin & Finance':'행정·재무','Recruitment & HR':'채용·인사',Academy:'아카데미','Dream House':'드림하우스',Communications:'홍보·커뮤니케이션',Teaching:'교육'}
export const REQUIREMENT_KO: Record<string,string> = {psa:'출생증명서 (PSA)',gov_id:'정부 신분증 사본',nbi:'NBI 신원조회서',police:'경찰 확인서',barangay:'바랑가이 확인서',sss:'SSS 번호',philhealth:'PhilHealth 번호',pagibig:'Pag-IBIG 번호',tin:'납세자 번호 (TIN)',diploma:'졸업증명서',tor:'성적증명서',marriage:'혼인증명서',solo_parent:'한부모 신분증',bir_2305:'BIR 2305 / 1905',bir_form:'최근 BIR 2316',coe:'전 직장 재직증명서'}
