"use client";
import { useState } from "react";
import "./student-views.css";

export type ViewStudent = {key:string;korName:string;engName:string;grade:string;age:string;academyStart:string;academyEnd:string;academyWeeks:string;checkin_date:string;checkout_date:string;reservation_no:string;booker_name:string;photo:string;special_request:string;assignee:string;care_assignee:string;};
const short=(v:string)=>v?v.slice(5).replaceAll("-","."):"미정";
const name=(s:ViewStudent)=>s.korName||s.engName||"이름 미입력";
const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function remaining(s:ViewStudent){if(!s.academyEnd)return "기간 미정";const now=new Date();const days=Math.round((Date.parse(s.academyEnd)-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);return days<0?"수료":days===0?"오늘 종료":days+"일";}

export function StudentViews<T extends ViewStudent>({rows,list=false,room,onCare,onBooking,onCopy,onNote}:{rows:T[];list?:boolean;room:(s:T)=>string;onCare:(s:T)=>void;onBooking:(s:T)=>void;onCopy:(s:T)=>void;onNote:(s:T)=>void}){
 const [key,setKey]=useState<string|null>(null),[detailTab,setDetailTab]=useState("basic"),[grade,setGrade]=useState("");
 const visible=rows.filter(s=>!grade||s.grade===grade);
 const selected=visible.find(s=>s.key===key)||visible[0];
 function select(s:T){setKey(s.key);setDetailTab("basic");}
 const info=selected&&<aside className="sl-detail" aria-label="학생 상세"><div className="sl-detail-heading"><span>학생 상세 보기</span></div><h2>{name(selected)} <small>{selected.engName}</small></h2><div className="sl-detail-meta"><span className={'sl-badge '+(selected.grade==="킨더"?'kinder':'junior')}>{selected.grade||"미지정"}</span><span>한국인 담당 <b>{selected.assignee||"미지정"}</b></span></div><div className="sl-detail-tabs" role="tablist" aria-label="학생 상세 항목">{[["basic","기본정보"],["care","수업 · 케어"],["booking","예약"]].map(([id,label])=><button role="tab" aria-selected={detailTab===id} key={id} onClick={()=>setDetailTab(id)}>{label}</button>)}</div>
 {detailTab==="basic"&&<><dl>{[["예약번호",selected.reservation_no],["예약자",selected.booker_name],["나이",selected.age],["숙소 · 호실",room(selected)],["수업 기간",`${selected.academyStart||"미정"} ~ ${selected.academyEnd||"미정"}`],["체크인 / 아웃",`${short(selected.checkin_date)} / ${short(selected.checkout_date)}`],["사진허용",selected.photo||"미입력"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"미입력"}</dd></div>)}</dl><h3>특이사항</h3><p className="sl-note">{selected.special_request||"등록된 특이사항이 없습니다."}</p><button className="sl-text-button" onClick={()=>onNote(selected)}>특이사항 수정</button></>}
 {detailTab==="care"&&<div className="sl-care"><h3>수업 및 학생케어</h3><p>{selected.academyStart||"미정"} ~ {selected.academyEnd||"미정"}</p><p>케어 담당: {selected.care_assignee||"미지정"}</p><p>학생케어에서 실제 수업 기록과 선생님 코멘트를 확인할 수 있습니다.</p></div>}
 {detailTab==="booking"&&<><dl>{[["예약번호",selected.reservation_no],["예약자",selected.booker_name],["체크인",selected.checkin_date],["체크아웃",selected.checkout_date],["숙소 · 호실",room(selected)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"미정"}</dd></div>)}</dl><div className="sl-detail-actions"><button onClick={()=>onBooking(selected)}>예약 상세 열기 ↗</button><button onClick={()=>onCopy(selected)}>재방문 예약 복사</button></div></>}
 <button className="sl-care-open" onClick={()=>onCare(selected)}>학생 케어 보기 ↗</button></aside>;
 const table=(items:T[],compact=false)=><div className="sl-table-scroll"><table className="sl-table"><thead><tr><th>학생</th>{!compact&&<th>과정</th>}<th>숙소 · 호실</th><th>수업 기간</th>{list&&<th>예약자</th>}<th>한국인 담당</th><th>남은 기간</th>{list&&<><th>사진허용</th><th>특이사항</th><th>재방문</th></>}</tr></thead><tbody>{items.map(s=><tr key={s.key} className={selected?.key===s.key?"is-selected":""}><td><button className="sl-student-name" onClick={()=>select(s)}>{name(s)}<small>{s.engName||"영문명 미입력"}</small></button></td>{!compact&&<td><span className={'sl-badge '+(s.grade==="킨더"?'kinder':'junior')}>{s.grade||"미지정"}</span></td>}<td>{room(s)||"미정"}</td><td className="sl-dates">{short(s.academyStart)} – {short(s.academyEnd)}{s.academyWeeks&&<small>{s.academyWeeks}주</small>}</td>{list&&<td>{s.booker_name||"미입력"}</td>}<td>{s.assignee||"미지정"}</td><td><span className={remaining(s).includes("종료")||/^[1-7]일$/.test(remaining(s))?"sl-ending":""}>{remaining(s)}</span></td>{list&&<><td>{s.photo||"미입력"}</td><td><button className="sl-note-link" onClick={()=>onNote(s)}>{s.special_request||"+ 추가"}</button></td><td><button className="sl-copy" onClick={()=>onCopy(s)}>예약 복사</button></td></>}</tr>)}</tbody></table>{!items.length&&<p className="sv-empty">조건에 맞는 학생이 없습니다.</p>}</div>;
 return <div className="sl-roster sl-roster-a sl-ivory-roster"><div className="sl-summary">{[["전체",rows.length],["킨더",rows.filter(s=>s.grade==="킨더").length],["주니어",rows.filter(s=>s.grade==="주니어").length]].map(([label,count])=><div key={label}><span>{label}</span><b>{count}<small>명</small></b></div>)}</div>
 {<div className="sl-grade-filter" aria-label="과정 필터">{["","킨더","주니어"].map(g=><button key={g} aria-pressed={grade===g} onClick={()=>setGrade(g)}>{g||"전체"}</button>)}</div>}
 <div className="sl-master-detail"><div>{!list?<div className="sl-split">{["킨더","주니어","과정 미지정"].map(g=>{const items=visible.filter(s=>g==="과정 미지정"?!["킨더","주니어"].includes(s.grade):s.grade===g);return !items.length&&g==="과정 미지정"?null:<section key={g}><h3>{g}<span>{items.length}명</span></h3>{table(items,true)}</section>;})}</div>:table(visible)}</div>{info||<aside className="sl-detail">표시할 학생이 없습니다.</aside>}</div>

</div>;
}

export function StudentTimeline<T extends ViewStudent>({rows,year,month,onSelect}:{rows:T[];year:number;month:number;onSelect:(s:T)=>void}){
 const days=new Date(year,month,0).getDate(),first=Date.UTC(year,month-1,1),last=first+(days-1)*86400000;
 const valid=rows.filter(s=>s.academyStart&&s.academyEnd&&Date.parse(s.academyStart)<=last&&Date.parse(s.academyEnd)>=first);
 return <div className="sl-timeline cal-wrap"><div className="sl-section-heading"><div><h2>수업 일정 <small>기간을 한눈에</small></h2><p>{year}년 {month}월 · 학생 이름 또는 기간을 누르면 학생케어를 엽니다.</p></div><span>🟢 킨더　🔵 주니어</span></div><div className="sl-table-scroll"><div className="sl-time-grid"><div className="sl-time-header"><b>학생</b><div>{Array.from({length:Math.ceil(days/7)},(_,i)=><span key={i} style={{width:Math.min(7,days-i*7)/days*100+'%'}}>{month}/{i*7+1} ~ {Math.min(days,i*7+7)}<small>재학 {valid.filter(s=>Date.parse(s.academyStart)<=first+(Math.min(days,i*7+7)-1)*86400000&&Date.parse(s.academyEnd)>=first+i*7*86400000).length}명</small></span>)}</div></div>{valid.map(s=>{const start=Math.max(0,Math.round((Date.parse(s.academyStart)-first)/86400000));const end=Math.min(days-1,Math.round((Date.parse(s.academyEnd)-first)/86400000));return <div className="sl-time-row" key={s.key}><button className="sl-student-name" onClick={()=>onSelect(s)}>{name(s)}<small>{s.engName} · {s.assignee||"담당 미지정"}</small></button><div className="sl-track" style={{backgroundSize:`${7/days*100}% 100%`}}><button className={s.grade==="킨더"?"kinder":"junior"} title={`${s.academyStart} ~ ${s.academyEnd}`} onClick={()=>onSelect(s)} style={{left:`${start/days*100}%`,width:`${(end-start+1)/days*100}%`}}>{short(s.academyStart)} – {short(s.academyEnd)}</button></div></div>;})}{!valid.length&&<p className="sv-empty">선택 기간에 학생이 없습니다.</p>}</div></div></div>;
}

export function StudentMonthCalendar<T extends ViewStudent>({rows,year,month,half,onMonth,onSelect}:{rows:T[];year:number;month:number;half:string;onMonth:(year:number,month:number)=>void;onSelect:(s:T)=>void}){
 const [chosen,setChosen]=useState("");const first=new Date(year,month-1,1),offset=(first.getDay()+6)%7;const start=new Date(year,month-1,1-offset);const weekCount=Math.ceil((offset+new Date(year,month,0).getDate())/7);
 const selectedDate=chosen.split("|")[0]===`${year}-${month}`?chosen.split("|")[1]:ymd(first);
 const selectedEvents=rows.flatMap(s=>[...(s.academyStart===selectedDate?[{s,type:"입학"}]:[]),...(s.academyEnd===selectedDate?[{s,type:"수료"}]:[])]);
 function shift(n:number){const d=new Date(year,month-1+n,1);onMonth(d.getFullYear(),d.getMonth()+1);}
 return <div className="sl-month cal-wrap"><div className="sl-section-heading"><div><h2>학생 달력</h2><p>입학 · 수료 학생 이름을 모두 표시합니다. 날짜를 누르면 상세 명단을 확인합니다.</p></div><div className="sl-month-nav"><button onClick={()=>shift(-1)} aria-label="이전달">‹</button><b>{year}년 {month}월</b><button onClick={()=>shift(1)} aria-label="다음달">›</button></div></div><div className="sl-month-layout"><div className="sl-table-scroll"><table className="sl-month-table"><thead><tr><th>주간 인원</th>{["월","화","수","목","금","토","일"].map(d=><th key={d}>{d}</th>)}</tr></thead><tbody>{Array.from({length:weekCount},(_,w)=>{const dates=Array.from({length:7},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+w*7+i));if(half!=="all"&&!dates.some(d=>d.getMonth()===month-1&&(half==="1st"?d.getDate()<=15:d.getDate()>=16)))return null;const active=rows.filter(s=>(s.korName||s.engName)&&!(s.korName==="-"&&(!s.engName||s.engName==="-"))&&s.academyStart&&s.academyStart<=ymd(dates[6])&&(s.academyEnd||s.academyStart)>=ymd(dates[0]));return <tr key={w}><th className="sl-week-count"><b>전체 {active.length}</b><span>킨더 {active.filter(s=>s.grade==="킨더").length}</span><span>주니어 {active.filter(s=>s.grade==="주니어").length}</span></th>{dates.map(d=>{const date=ymd(d),ins=rows.filter(s=>s.academyStart===date),outs=rows.filter(s=>s.academyEnd===date);return <td key={date} className={(d.getMonth()!==month-1?"outside ":"")+(selectedDate===date?"chosen":"")}><button className="sl-day" aria-label={`${date} 입학 ${ins.length}명 수료 ${outs.length}명`} aria-pressed={selectedDate===date} onClick={()=>setChosen(`${year}-${month}|${date}`)}><b>{d.getDate()}</b>{ins.length>0&&<span className="sl-event in">입학 {ins.length}명<span className="sl-event-names">{ins.map(s=><span className="sl-event-student" key={s.key}><strong>{name(s)}</strong>{s.engName && s.engName!=="-" && s.engName!==name(s) && <span className="sl-event-english">{s.engName}</span>}</span>)}</span></span>}{outs.length>0&&<span className="sl-event out">수료 {outs.length}명<span className="sl-event-names">{outs.map(s=><span className="sl-event-student" key={s.key}><strong>{name(s)}</strong>{s.engName && s.engName!=="-" && s.engName!==name(s) && <span className="sl-event-english">{s.engName}</span>}</span>)}</span></span>}</button></td>;})}</tr>;})}</tbody></table></div><aside className="sl-day-detail"><h3>{short(selectedDate)} <small>입학 · 수료 명단</small></h3>{selectedEvents.map(({s,type})=><button key={s.key+type} onClick={()=>onSelect(s)}><span className={type==="입학"?"sl-in":"sl-out"}>{type}</span><b>{name(s)}</b><small>{s.grade||"미지정"} · {s.assignee||"담당 미지정"}</small></button>)}{!selectedEvents.length&&<p>입학 · 수료 일정이 없습니다.</p>}</aside></div></div>;
}


