'use client'
import {useCallback,useEffect,useState} from 'react'
import PayrollWorkspace from '@/app/admin/HR/PayrollWorkspace'
import {SELF_FIELDS,SELF_MISSING} from '@/lib/hrSelfFields'
import {COMPANY_EN} from '@/lib/hrFields'
import '@/app/admin/HR/hr.css'
export default function MyProfile(){
 const [profile,setProfile]=useState<Record<string,any>|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState('profile'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[mustChange,setMustChange]=useState(false)
 const [payItems,setPayItems]=useState<any[]>([])
 const request=useCallback(async(url:string,init?:RequestInit)=>{const res=await fetch(url.replace('/api/hr/payroll','/api/staff/my-payroll'),{...init,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'}});const body=await res.json();if(!res.ok)throw Error(body.error||'Unable to load. Please retry.');return body},[])
 const load=useCallback(async()=>{try{const r=await request('/api/staff/my-profile');setProfile(r.employee);setPayItems(r.pay_items||[]);setMustChange(r.must_change_pw);setDirty(false);setError('')}catch(e){setError((e as Error).message)}},[request])
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty])
 const missing=profile?SELF_MISSING.filter(k=>!String(profile[k]??'').trim()):[]
 return <main className="hr-app" style={{maxWidth:1200,margin:'0 auto',padding:24}}><header className="hr-page-heading"><div><p className="hr-eyebrow">MY STAFF SPACE</p><h1>Personal profile & pay</h1><p>Your own employee information, timecards and payslips.</p></div><a href="/admineng/hub" className="hr-btn">Back to staff home</a></header>
 {error&&<p className="hr-alert" role="alert">{error} <button className="hr-btn" onClick={()=>{if(!dirty||confirm('Discard unsaved edits and reload?'))void load()}}>Reload</button></p>}
 {mustChange?<section className="hr-card"><h2>Change your temporary password first</h2><a href="/admineng/hub">Return to staff home to change your password</a></section>:profile?<><div className="hr-inline" style={{marginBottom:24}}>{[['profile','Personal profile'],['pay','Pay information'],['time','Timecards & payslips']].map(([key,label])=><button key={key} className={'hr-btn '+(tab===key?'primary':'')} onClick={()=>{if(dirty&&!confirm('Discard unsaved edits?'))return;if(dirty)void load();setDirty(false);setMessage('');setTab(key)}}>{label}{key==='profile'&&missing.length>0&&<span style={{color:'#b42318',marginLeft:8}}>! {missing.length}</span>}</button>)}</div>
 {message&&<p role="status" className="hr-success">{message}</p>}
 {tab==='profile'?<form className="hr-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/api/staff/my-profile',{method:'PATCH',body:JSON.stringify({updated_at:profile.updated_at,values:Object.fromEntries(SELF_FIELDS.map(([k])=>[k,String(profile[k]??'')]))})});await load();setMessage('Your profile has been saved to HR.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><h2>{profile.first_name} {profile.last_name}</h2><p>{COMPANY_EN[profile.company]||profile.company} · {profile.employee_id} · {profile.position}</p><p>Complete missing details marked with a red !. If an ID has not been issued yet, leave it blank and contact HR.</p><div className="hr-field-grid">{SELF_FIELDS.map(([key,label])=><label key={key}>{label}{missing.includes(key as typeof SELF_MISSING[number])&&<span style={{color:'#b42318'}} aria-label="Missing information"> !</span>}<input disabled={busy} type={key==='date_of_birth'?'date':key==='personal_email'?'email':'text'} required={key==='first_name'||key==='last_name'} maxLength={500} value={profile[key]??''} onChange={e=>{setDirty(true);setMessage('');setProfile({...profile,[key]:e.target.value})}}/></label>)}</div><div className="hr-savebar"><span>{dirty?'Unsaved changes':'Your information is linked to HR.'}</span><button className="hr-btn primary" disabled={busy}>{busy?'Saving…':'Save profile to HR'}</button></div></form>:tab==='pay'?<section className="hr-card"><h2>My pay information</h2><p>These values come from your HR profile. Ask HR to correct salary or deduction rates.</p><dl className="hr-summary-grid">{[['salary_type','Pay basis'],['basic_salary','Base salary (PHP)'],['allow_position','Position allowance'],['allow_transpo','Transport allowance'],['allow_tutorial','Tutorial allowance'],['allow_load','Load allowance'],['time_in','Scheduled clock-in'],['time_out','Scheduled clock-out']].map(([k,label])=><div key={k}><dt>{label}</dt><dd>{profile[k]??(k==='time_in'?'08:30':k==='time_out'?'17:00':'Not entered by HR')}</dd></div>)}</dl><h3>Personal pay and deduction overrides</h3>{payItems.filter(r=>r.active&&r.id!=='basic').map(r=><p key={r.id}><strong>{r.name}</strong> · {r.kind==='deduction'?'Deduction':'Earning'}: {profile.payroll_values?.[r.id]??r.amount} ({r.method}) · Payday {r.schedule==='both'?'5th & 20th':r.schedule}</p>)}<p>Final payslips are available under Timecards & payslips after HR approval.</p></section>:<PayrollWorkspace request={request} language="en" onDirty={setDirty}/>}</>:!error?<p>Loading your profile…</p>:null}
 </main>
}


