'use client';
import {useEffect,useRef,useState} from 'react';
import {defaultDates,textBlocks,blockText,type Activity,type Template,type Block} from '@/lib/fieldtripWorkspace';
import './workspace.css';
type MonthData={items:Activity[];live:Activity[];revision:number;fingerprint:string;currentFingerprint:string;conflict:boolean;templates?:Template[]};
const label=(type:string)=>type==='fieldtrip'?'필드트립':'애프터스쿨';
const keyMonth=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}).slice(0,7);
async function api(query='',body?:unknown){const r=await fetch('/api/staff/fieldtrip-workspace'+query,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'요청 실패');return data;}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="fw-modal" onCancel={e=>{e.preventDefault();onClose();}}><header><h2>{title}</h2><button onClick={onClose} aria-label="닫기">×</button></header>{children}</dialog>;}
function Blocks({blocks,onChange}:{blocks:Block[];onChange:(b:Block[])=>void}){const update=(i:number,p:Partial<Block>)=>onChange(blocks.map((b,n)=>i===n?{...b,...p}:b));return <><div className="fw-blocks">{blocks.map((b,i)=><section key={b.id} style={{gridColumn:`span ${b.width}`}}><div className="fw-block-tools"><button disabled={i===0} onClick={()=>{const a=[...blocks];[a[i-1],a[i]]=[a[i],a[i-1]];onChange(a);}} aria-label={`항목 ${i+1} 위로`}>↑</button><button disabled={i===blocks.length-1} onClick={()=>{const a=[...blocks];[a[i+1],a[i]]=[a[i],a[i+1]];onChange(a);}} aria-label={`항목 ${i+1} 아래로`}>↓</button><select aria-label={`항목 ${i+1} 너비`} value={b.width} onChange={e=>update(i,{width:Number(e.target.value) as 1|2})}><option value={1}>반 너비</option><option value={2}>전체 너비</option></select><select aria-label={`항목 ${i+1} 높이`} value={b.height} onChange={e=>update(i,{height:Number(e.target.value)})}>{Array.from(new Set([100,140,180,260,400,b.height])).sort((a,b)=>a-b).map(h=><option key={h} value={h}>높이 {h}</option>)}</select><button className="fw-danger" onClick={()=>{if(confirm('이 항목을 삭제할까요? 저장 전에는 취소할 수 있습니다.'))onChange(blocks.filter((_,n)=>n!==i));}} aria-label={`항목 ${i+1} 삭제`}>×</button></div><input aria-label={`항목 ${i+1} 제목`} value={b.title} placeholder="항목 제목" onChange={e=>update(i,{title:e.target.value})}/><textarea aria-label={`항목 ${i+1} 내용`} value={b.text} style={{minHeight:b.height}} onChange={e=>update(i,{text:e.target.value})}/></section>)}</div><button onClick={()=>onChange([...blocks,{id:crypto.randomUUID(),title:'새 항목',text:'',width:1,height:140}])}>＋ 항목 추가</button></>;}
function Preview({title,blocks}:{title:string;blocks:Block[]}){return <article className="fw-paper"><div className="fw-paper-brand">Dream Academy <small>필드트립 · 애프터스쿨</small></div><h2>{title}</h2><div className="fw-blocks">{blocks.map(b=><section key={b.id} style={{gridColumn:`span ${b.width}`,minHeight:b.height}}><h3>{b.title}</h3><p>{b.text}</p></section>)}</div></article>;}
export default function FieldtripWorkspace(){
 const [month,setMonth]=useState(keyMonth),[data,setData]=useState<MonthData|null>(null),[items,setItems]=useState<Activity[]>([]),[templates,setTemplates]=useState<Template[]>([]),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[editing,setEditing]=useState<Activity|null>(null),[template,setTemplate]=useState<Template|null>(null),[templateDirty,setTemplateDirty]=useState(false),[preview,setPreview]=useState<{title:string;blocks:Block[]}|null>(null),[publish,setPublish]=useState(false),[history,setHistory]=useState<{revision:number;data:Template;created_at:string}[]|null>(null);
 const request=useRef(0);
 async function load(){const version=++request.current;setBusy(true);setError('');try{const d=await api('?month='+month);if(version!==request.current)return;setData(d);setItems(d.items);setTemplates(d.templates);setDirty(false);}catch(e){if(version===request.current)setError((e as Error).message);}finally{if(version===request.current)setBusy(false);}}
 useEffect(()=>{load();return()=>{request.current++;};},[month]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty||templateDirty||editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);const w=window as unknown as {fieldtripUnsaved:boolean};w.fieldtripUnsaved=dirty||templateDirty||!!editing;return()=>{window.removeEventListener('beforeunload',fn);w.fieldtripUnsaved=false;};},[dirty,templateDirty,editing]);
 const notify=(text:string)=>{setMessage(text);setError('');};
 function changeMonth(value:string){if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(value))return;if(dirty&&!confirm('저장하지 않은 일정 변경이 있습니다. 버리고 이동할까요?'))return;setData(null);setMonth(value);}
 function shift(n:number){const [y,m]=month.split('-').map(Number),d=new Date(y,m-1+n,1);changeMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);}
 async function save(){if(!data)return;setBusy(true);try{const d=await api('',{action:'save',month,revision:data.revision,fingerprint:data.fingerprint,items});setData(d);setItems(d.items);setDirty(false);notify('작성 중인 일정을 저장했습니다. 아직 부모님 화면에는 반영되지 않았습니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function deploy(){if(!data||dirty)return;setBusy(true);try{const d=await api('',{action:'publish',month,revision:data.revision,fingerprint:data.fingerprint});setData(d);setItems(d.items);setPublish(false);notify('배포했습니다. 부모님 신청 화면과 기존 직원 신청목록에 연결됩니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function chooseDate(date:string){setError('');const existing=items.find(i=>i.date===date);setEditing(existing?structuredClone(existing):{id:crypto.randomUUID(),date,type:defaultDates(month).find(d=>d.date===date)?.type||'fieldtrip',title:'',description:'',blocks:[]});}
 function applyTemplate(t:Template){if(!editing){notify('먼저 달력에서 날짜를 선택해주세요.');return;}if(editing.title&&!confirm('이 날짜의 작성 내용을 선택한 템플릿으로 바꿀까요? 원본 템플릿은 유지됩니다.'))return;const blocks=structuredClone(t.blocks).map(b=>({...b,text:b.text.replaceAll('[날짜]',editing.date).replaceAll('[요일]',['일','월','화','수','목','금','토'][new Date(editing.date+'T12:00:00').getDay()])}));setEditing({...editing,title:t.title,type:t.type,blocks,description:blockText(blocks),templateId:t.id});}
 function editTemplate(t:Template){setError('');setTemplate(structuredClone(t));setTemplateDirty(false);setHistory(null);}
 async function saveTemplate(copy=false){if(!template||!template.title.trim())return;setBusy(true);try{const t={...template,id:copy||!template.id.startsWith('template:')?'template:'+crypto.randomUUID():template.id,revision:copy||!template.id.startsWith('template:')?0:template.revision};const r=await api('',{action:'template',template:t});const saved={...t,revision:r.revision,source:'저장한 템플릿'};setTemplates(a=>[saved,...a.filter(x=>x.id!==saved.id)]);setTemplate(saved);setTemplateDirty(false);setHistory(null);notify('템플릿을 저장했습니다. 다른 일정에서도 불러올 수 있습니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const [y,m]=month.split('-').map(Number),start=(new Date(y,m-1,1).getDay()+6)%7,days=new Date(y,m,0).getDate(),defaults=defaultDates(month);
 const visible=templates.filter(t=>(filter==='all'||t.type===filter)&&(!search||(t.title+' '+t.source).toLowerCase().includes(search.toLowerCase())));
 const changed=items.filter(i=>{const l=data?.live.find(l=>l.id===i.id);return !l||!l.is_deployed||l.title!==i.title||l.date!==i.date||l.description!==i.description||l.type!==i.type;}).length;
 return <div className="fw"><div className="fw-status"><span>필드트립 <strong>매월 둘째·넷째 토요일</strong> · 애프터스쿨 월·수</span><span>날짜 선택 → 내용 저장 → 미리보기·배포</span></div>{error&&<div role="alert" className="fw-error">{error}<button disabled={busy} onClick={()=>{if(!dirty||confirm('현재 편집을 버리고 다시 불러올까요?'))load();}}>다시 불러오기</button></div>}{message&&<p className="fw-message" role="status">{message}</p>}
 <div className="fw-layout"><section className="fw-calendar"><header className="fw-toolbar"><button aria-label="이전 달" disabled={busy} onClick={()=>shift(-1)}>‹</button><input aria-label="일정 월" type="month" value={month} disabled={busy} onChange={e=>changeMonth(e.target.value)}/><button aria-label="다음 달" disabled={busy} onClick={()=>shift(1)}>›</button><span className="fw-spacer"/><button disabled={busy||!dirty||!data||data.conflict} onClick={save}>내용 저장{dirty?' ●':''}</button><button className="fw-primary" disabled={busy||dirty||!data||!items.length||!data.revision||data.conflict} onClick={()=>{setError('');setPublish(true);}}>미리보기 · 배포</button></header><div className="fw-legend"><span>● 애프터스쿨</span><span>● 필드트립</span><small>{busy?'불러오는 중…':dirty?'저장하지 않은 변경 있음':changed?`배포 전 변경 ${changed}건`:'배포된 일정'} {data?.conflict?'· 다른 화면 변경 감지':''}</small></div>
 {data?.conflict&&<div role="alert" className="fw-error">기존 화면에서 일정이 변경되었습니다. 현재 배포 일정을 불러온 뒤 다시 편집해주세요.<button disabled={busy} onClick={()=>{if(confirm('작성 중인 초안을 현재 배포 일정으로 바꿀까요? 기존 저장 이력은 보존됩니다.')){setItems(data.live);setData({...data,fingerprint:data.currentFingerprint,conflict:false});setDirty(true);notify('현재 배포 일정을 불러왔습니다. 편집 후 내용 저장을 눌러주세요.');}}}>현재 배포 일정 불러오기</button></div>}<div className="fw-grid">{['월','화','수','목','금','토','일'].map(d=><div key={d} className="fw-dow">{d}</div>)}{Array.from({length:Math.ceil((start+days)/7)*7},(_,cell)=>{const day=cell-start+1;if(day<1||day>days)return <div key={'empty'+cell} className="fw-blank"/>;const date=`${month}-${String(day).padStart(2,'0')}`,rows=items.filter(i=>i.date===date),def=defaults.find(d=>d.date===date);return <button key={date} disabled={busy||!data} className={'fw-day '+(def?.type==='fieldtrip'?'fw-default':'')} onClick={()=>chooseDate(date)} aria-label={`${date} 일정 편집`}><strong>{day}</strong>{rows.map(i=><span key={i.id} className={'fw-pill '+i.type}>{i.title}</span>)}{!rows.length&&def&&<span className="fw-empty-day">＋ {label(def.type)}</span>}</button>;})}</div><p className="fw-help">날짜를 눌러 활동을 선택하세요. 저장한 내용은 배포 전까지 직원에게만 보입니다.</p></section>
 <aside className="fw-library"><header><h2>템플릿 보관함 <small>{templates.length}</small></h2><button onClick={()=>editTemplate({id:'template:'+crypto.randomUUID(),title:'',type:'fieldtrip',revision:0,blocks:[{id:crypto.randomUUID(),title:'안내 내용',text:'',width:2,height:180}]})}>＋ 새 템플릿</button></header><input aria-label="템플릿 검색" placeholder="활동·템플릿 검색" value={search} onChange={e=>setSearch(e.target.value)}/><div className="fw-filters">{[['all','전체'],['fieldtrip','필드트립'],['afterschool','애프터스쿨']].map(([v,n])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{n}</button>)}</div><p className="fw-help">기존 자료는 원본으로 유지됩니다. 편집 후 새 양식으로 저장하세요.</p><div className="fw-cards">{visible.map(t=><article key={t.id}><button className="fw-thumbnail" aria-label={t.title+' 미리보기'} onClick={()=>setPreview({title:t.title,blocks:t.blocks})}><div>Dream Academy</div>{t.blocks.slice(0,4).map(b=><p key={b.id}>{b.title}<br/>{b.text.slice(0,60)}</p>)}</button><small>{t.source}</small><h3>{t.title}</h3><footer><button onClick={()=>editTemplate(t)}>편집</button><button onClick={()=>{if(!editing){setError('');const date=defaults.find(d=>d.type===t.type&&!items.some(i=>i.date===d.date&&i.type===t.type))?.date||month+'-01';const blocks=structuredClone(t.blocks).map(b=>({...b,text:b.text.replaceAll('[날짜]',date).replaceAll('[요일]',['일','월','화','수','목','금','토'][new Date(date+'T12:00:00').getDay()])}));setEditing({id:crypto.randomUUID(),date,type:t.type,title:t.title,description:blockText(blocks),blocks,templateId:t.id});}else applyTemplate(t);}}>일정에 사용</button></footer></article>)}</div>{!busy&&!visible.length&&<p>해당하는 템플릿이 없습니다.</p>}<a href="/admin/notices/fieldtrip/skating/staff-guide" target="_blank" rel="noopener">기존 필드트립 준비가이드 ↗</a></aside></div>
 {editing&&<Modal title={`${editing.date} 활동 선택`} onClose={()=>{if(confirm('작성 중인 날짜 설정을 닫을까요? 적용하지 않은 내용은 저장되지 않습니다.'))setEditing(null);}}><div className="fw-modal-body">{error&&<p role="alert" className="fw-error">{error}</p>}<div className="fw-two"><label>날짜<input type="date" aria-label="활동 날짜" min={month+'-01'} max={month+'-'+days} value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label><label>유형<select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as Activity['type']})}><option value="fieldtrip">필드트립</option><option value="afterschool">애프터스쿨</option></select></label></div><label>기존 템플릿 불러오기<select aria-label="일정 템플릿" value="" onChange={e=>{const t=templates.find(t=>t.id===e.target.value);if(t)applyTemplate(t);}}><option value="">활동 선택 — 직접 입력도 가능합니다</option>{templates.filter(t=>t.type===editing.type).map(t=><option key={t.id} value={t.id}>{t.title} · {t.source}</option>)}</select></label><label>활동명<input aria-label="활동명" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>내용<textarea aria-label="활동 내용" rows={7} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value,blocks:textBlocks(e.target.value)})}/></label><p className="fw-help">기존 문구의 날짜·시간·준비물도 확인해주세요. 이 날짜의 내용을 바꿔도 원본 템플릿은 바뀌지 않습니다.</p></div><footer><button onClick={()=>{if(!editing.title)return;editTemplate({id:'template:'+crypto.randomUUID(),title:editing.title,type:editing.type,blocks:editing.blocks?.length?editing.blocks:textBlocks(editing.description),revision:0});}}>이 내용을 템플릿으로 저장</button><button className="fw-primary" disabled={!editing.title.trim()||!editing.date.startsWith(month+'-')} onClick={()=>{if(items.some(i=>i.id!==editing.id&&i.date===editing.date&&i.type===editing.type)){setError('같은 날짜·유형의 일정이 이미 있습니다.');return;}setItems(a=>[...a.filter(i=>i.id!==editing.id),editing].sort((a,b)=>a.date.localeCompare(b.date)));setDirty(true);setEditing(null);notify('달력에 적용했습니다. 내용 저장 후 배포해주세요.');}}>달력에 적용</button></footer></Modal>}
 {template&&<Modal title="템플릿 편집" onClose={()=>{if(!templateDirty||confirm('저장하지 않은 템플릿 변경을 버릴까요?')){setTemplate(null);setTemplateDirty(false);}}}><div className="fw-modal-body"><p className="fw-help">네모 항목을 추가·삭제하고 너비·높이·순서를 조정할 수 있습니다. {template.source}</p>{error&&<p role="alert" className="fw-error">{error}</p>}<div className="fw-two"><label>템플릿 이름<input aria-label="템플릿 이름" value={template.title} onChange={e=>{setTemplate({...template,title:e.target.value});setTemplateDirty(true);}}/></label><label>유형<select value={template.type} onChange={e=>{setTemplate({...template,type:e.target.value as Template['type']});setTemplateDirty(true);}}><option value="fieldtrip">필드트립</option><option value="afterschool">애프터스쿨</option></select></label></div>{template.originalUrl&&<a href={template.originalUrl} target="_blank" rel="noopener">기존 고정 양식 원본 보기 ↗</a>}<Blocks blocks={template.blocks} onChange={blocks=>{setTemplate({...template,blocks});setTemplateDirty(true);}}/>{history&&<section><h3>저장 이력</h3>{history.length===0?<p>이전 저장본이 없습니다.</p>:history.map(h=><button key={h.revision} onClick={()=>{if(confirm('이 저장본을 편집 화면에 불러올까요? 저장 버튼을 눌러야 반영됩니다.')){setTemplate({...template,title:h.data.title,type:h.data.type,blocks:h.data.blocks});setTemplateDirty(true);}}}>버전 {h.revision} · {new Date(h.created_at).toLocaleString('ko-KR')}</button>)}</section>}</div><footer>{template.id.startsWith('template:')&&template.revision>0&&<button onClick={async()=>{try{const r=await api('?history='+encodeURIComponent(template.id));setHistory(r.history);}catch(e){setError((e as Error).message);}}}>저장 이력</button>}<button onClick={()=>setPreview({title:template.title,blocks:template.blocks})}>미리보기</button><button disabled={busy||!template.title.trim()} onClick={()=>saveTemplate(true)}>다른 템플릿으로 저장</button><button className="fw-primary" disabled={busy||!template.title.trim()} onClick={()=>saveTemplate()}>{template.id.startsWith('template:')?'저장':'원본 유지 · 새 양식 저장'}</button></footer></Modal>}
 {preview&&<Modal title="안내문 미리보기" onClose={()=>setPreview(null)}><div className="fw-modal-body">{error&&<p role="alert" className="fw-error">{error}</p>}<Preview {...preview}/></div><footer><button onClick={async()=>{try{await navigator.clipboard.writeText(blockText(preview.blocks));notify('내용을 복사했습니다.');}catch{setError('복사 권한을 확인해주세요.');}}}>내용 복사</button><button onClick={()=>window.print()}>인쇄 · PDF 저장</button></footer></Modal>}
 {publish&&<Modal title={`${month} 배포 전 확인`} onClose={()=>!busy&&setPublish(false)}><div className="fw-modal-body">{error&&<p role="alert" className="fw-error">{error}</p>}<p>아래 {items.length}개 일정을 부모님 신청 화면에 공개합니다. 변경 {changed}건을 확인해주세요.</p>{items.map(i=><section key={i.id} className="fw-publish-row"><strong>{i.date} · {label(i.type)} · {i.title}</strong><p>{i.description||'추가 내용 없음'}</p></section>)}</div><footer><button disabled={busy} onClick={()=>setPublish(false)}>돌아가기</button><button disabled={busy||dirty} className="fw-primary" onClick={deploy}>{busy?'배포 중…':'확인 · 이번 달 배포'}</button></footer></Modal>}
 </div>;
}
